### ISSUE TITLE
Any plan to implement security (ACL) in Jester?

### ISSUE THREAD

**Issue by geohuz** [dom96/jester#112]
authentication and authorization based on ACL rules defined by user

**Comment by dom96** [comment]
Yes. But isn't ACL a Linux thing?

**Comment by girvo** [comment]
@dom96 I think @geohuz is speaking more generally; though I'm unsure how any sort of ACL layer would work in a generic HTTP microframework like this, without proscribing far too many bits and pieces... on the other hand, pretty easy to override functions procs and types, so it might actually be feasible.

**Comment by geohuz** [comment]
Yeah as I'm familiar with python's pyramid web framework, I'm trying to map some of the concepts from it. I think we can use the ACL concept in the auth/authorization in web app too. a typical ACL is defined like this:
`__acl__ = [
        (Allow, Everyone, 'view'),
        (Allow, 'group:editors', 'add'),
        (Allow, 'group:editors', 'edit'),
        ]`
So it's basically saying that a principal **Everyone** (framework predefined group) can have 'view' permission, **group:editors**(user defined group) have 'add' permission. And this ACL can then be applied to router.  And then there is a user defined callback function to return the principal base on the userid, sth like:
`def groupfinder(userid, request):
    if userid in USERS:
        return GROUPS.get(userid, [])
`
And finally we can add a **permission=** parameter to the router, so for '/edit_page', permission="edit"

I believe this design will provide a flexible and pluggable security system. And it's best explained in the documentation:  http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/security.html

**Comment by dom96** [comment]
Just to give an update on this: I think this should be implemented as an addition to Jester (a middleware, once Jester gets support for those).

**Comment by r-obert** [comment]
ime such features are implemented as third party plugins, pyramid is the first web framework i've seen that ships with the feature... but i'm not making an argument against doing that.
