### ISSUE TITLE
What's wrong with downloading big files?

### ISSUE THREAD

**Issue by shawnye** [dom96/jester#113]
There is non-trival example:

<pre>
settings:
    staticDir = "static"
    port = Port(8080)
routes:
  get "/":
    redirect(request.makeUri("/index.html") )   

runForever()   
</pre>

I just put a 9MB file inside `static` dir, and download it :
http://127.0.0.1:8080/test.zip,  it consumes memory from about 5MB to over 50MB,  

It seems full duplex pipeline( using `socketpair`) is not used. 
Is any way to  open it, thank you!

**Comment by yglukhov** [comment]
Might be related: https://github.com/nim-lang/Nim/issues/5589

**Comment by shawnye** [comment]
I build it with nim version 0.16.0, 0.16.1, 0.17.0 on windows server 2008 R2 , the `memory leak` problem keep with it.

**Comment by dom96** [comment]
This should be fixed and be even better once ``refresh`` is merged (soon).
