### ISSUE TITLE
[bug] request timeout on large files

### ISSUE THREAD

**Issue by samdmarshall** [dom96/jester#115]
I have a static site being served through Jester and I'm experiencing a bug where upon a request made to a large file, the rest times out. I've observed the following behaviors:

`0.1.1`: Request times out, the webserver stops responding
`devel`: Request times out, after the request times out the webserver will start responding again, but for the duration of the request it isn't responsive.

The file in question is ~550MB. The described behavior happens regardless of the type of request being made (tested with both `GET` and `HEAD`).

The code for the webserver is here: https://github.com/samdmarshall/pewpewthespells-com/blob/master/ritual.nim

**Comment by FedericoCeratto** [comment]
Looks like Jester is reading the whole file in memory and then serving it. Streaming contents on the fly would allow serving very large files.

**Comment by dom96** [comment]
The ``devel`` branch performs streaming IIRC.

Perhaps I will look into this on Saturday :)

**Comment by samdmarshall** [comment]
Is there anything to update for this? Willing to try out any experimental branches to see if there are any improvements.

**Comment by dom96** [comment]
Still the same advice. (But just try the latest master, the changes in `devel` have been merged in)

**Comment by dom96** [comment]
I'm going to optimistically say that this is fixed.
