### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by FedericoCeratto** [dom96/jester#119]
The following snippet builds using --threads=on but fails to run with:
`Error: unhandled exception: No handles or timers registered in dispatcher. [ValueError]`

```nim
routes: 
  get "/": 
    resp "Hello world" 
 
spawn runForever() 
sync() 
```
I suspect the routes macro "registers" the route only in the main thread somehow.

Possibly related to #117 #55

**Comment by dom96** [comment]
This won't be possible after ``refresh`` is merged.
