### ISSUE TITLE
Q: Large POST data results in HTTP response 413

### ISSUE THREAD

**Issue by ThomasTJdev** [dom96/jester#122]
Hi

When sending large amount of POST data, Jester is responding with '413 Request Entity Too Large'. 
I have set up a transparent proxy with Caddy to monitor the response, and here I am also getting '413 52 Request Entity Too Large'.

In my web app the user can write a long report and save it continuously with a simple ajax POST to the server. I have tried formatting the POST data to ensure, that it was not some special char, which was messing it up, (regex, encodeURIComponent(uri), etc.), but as stated by the 413 response, the only solution is to minimize the content length.

I have tried several combinations in Jester - but the only solution is to generate a file and upload it.
For reference only this function is needed:
```nim
post "/report":
  # Post is sent with: url.com/report?data=LongPostData
  # Post data is located in @"data"
  echo @"data"
```

In have not located a place to set the body size like Nginx, Caddy and Apache:
```config
client_max_body_size size;
limits size
LimitRequestBody
```

My program is compiled with `-d:ssl` - but the problem exists both on my local dev (HTTP) and in production (HTTPS).
I'm running:
```
System: Arch/Ubuntu
Nim: 0.17.2
Jester: 0.2.0
```

**Is there any configuration or setting I have missed, where I can set the allowed body size in Jester?**

**Comment by dom96** [comment]
This is likely an ``asynchttpserver`` issue. Looking at the code, it seems that code 413 is only returned when a single line is too long (this is only the case when reading the first line of the request or the headers): https://github.com/nim-lang/Nim/blob/devel/lib/pure/asynchttpserver.nim#L164 or https://github.com/nim-lang/Nim/blob/devel/lib/pure/asynchttpserver.nim#L208

The POST body isn't read this way. This is done here: https://github.com/nim-lang/Nim/blob/devel/lib/pure/asynchttpserver.nim#L229

Maybe you could look into this?

**Comment by ThomasTJdev** [comment]
Thank for the clarification @dom96! I will definitely look into it and (hopefully) come back with my solution :)!

**Comment by ThomasTJdev** [comment]
I have not been able to make a sustainable solution for now. I'll do some changes to my headers, and live with the POST data in the body for now, and - if I can not do without large headers (+ 8kb) - I'll resume the hunt, but over at the `asynchttpserver`.

But thank you for the help d0m96!
