### ISSUE TITLE
Some crashes

### ISSUE THREAD

**Issue by gcat432** [dom96/jester#123]
- Jester crashes when a non-conventional HTTP request method is sent. For example with the inexistant `COUNTER` method.
- Jester crashes randomly with the following error: `Error: unhandled exception: Expected authority got nothing. [ValueError]`

**Comment by Yardanico** [comment]
@gangsterakato I think you should report that in Nim repo - jester is built on top of asynchttpserver module, which is stdlib one

**Comment by dom96** [comment]
What @Yardanico said.

**Comment by dom96** [comment]
Reopening. Said on IRC that the author will add more info about how to reproduce.

**Comment by dom96** [comment]
Still waiting :/
