### ISSUE TITLE
Error: Address already in use

### ISSUE THREAD

**Issue by loongw** [dom96/jester#125]
I am making a "process monitor" with a web api.
Some times the monitor quit when children still running. 
I found that each child was still keeping the socket opening which the jester listen to.
This cause the next time trying to start the monitor failure.

From linux man page, we should set the socket(fd) with flag: O_CLOEXEC.
Is there any way I can get the underlying socket and set it's flag?

**Comment by dom96** [comment]
Huh, you shouldn't get that error because ``reuseAddr`` is always ``true``: https://github.com/nim-lang/Nim/blob/master/lib/pure/asynchttpserver.nim#L65

There is no way to get the underlying socket, you'll need to edit the asynchttpserver module and play around with it. If you fix your problem we can merge that into the Nim repo.

**Comment by loongw** [comment]
@dom96  I noticed the `reusePort` is `false` by default. Maybe this should export into jester's settings.
But that's not actually what I need.
I'll explore the jester and asynchttpserver's source to find a way to set the O_CLOEXEC flag.

**Comment by loongw** [comment]
This is a small example to reproduce the problem.
```nim
import asyncdispatch
import jester
import osproc
import posix


routes:
  get "/":
    resp "OK"

discard startProcess("/bin/sleep", args= @["100"])

callSoon do():
  exitNow(0)

runForever()
```

After exit:
```sh
$ netstat -nlp | grep 5000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      30684/sleep
```

**Comment by loongw** [comment]
I can't find a cross-platform style to edit the asynchttpserver source.
So as a workaround, I currently get all fds from `/proc/self/fd/` other than 0/1/2 and mark is as FD_CLOEXEC.

**Comment by dom96** [comment]
So it's as if the process is still running? That's really odd behaviour. But yes, this is a stdlib issue, I'll be closing this (thanks for opening that other issue).
