### ISSUE TITLE
🃏More Emojis🃏

### ISSUE THREAD

**Issue by dom96** [dom96/jester#137]
Developers love emojis.

**Comment by skellock** [comment]
🎺

**Comment by Araq** [comment]
Is this a joke?

**Comment by dom96** [comment]
Partially. It's for marketing.

**Comment by Araq** [comment]
Sorry but this is a serious project, valuable for Nim's infrastructure and I open the issue tracker and I see "More Emojis". You can guess my reaction.

**Comment by alehander42** [comment]
Emojis are extremely important for infrastructure

**Comment by dom96** [comment]
Damn right. 

We shouldn't take things so seriously all the time, it's nice to do some silly things once in a while. :)

**Comment by alehander42** [comment]
:+1: 

:haircut_man: :warning: :eyes: :clock1:

**Comment by LantosTG** [comment]
![image](https://user-images.githubusercontent.com/39604275/71573287-0519c200-2adb-11ea-8822-350fcf4f4cac.png)

**Comment by dom96** [comment]
@LantosTG PR? :D

**Comment by LantosTG** [comment]
sure
https://github.com/dom96/jester/pull/230
