### ISSUE TITLE
[REG] ~/.nimble_choosenim/pkgs/jester-0.2.0/jester.nim(531, 21) Error: type mismatch: got <Time> but expected 'int'

### ISSUE THREAD

**Issue by timotheecour** [dom96/jester#138]
@dom96 

regression: with latest nim
nim c -o:app -r bugs/t20_jester_type_mismatch.nim

```nim
# D20180415T214821
import jester
```

$HOME/.nimble_choosenim/pkgs/jester-0.2.0/jester.nim(531, 21) Error: type mismatch: got <Time> but expected 'int'

**Comment by timotheecour** [comment]
actually, this was fixed in master; could jester update it's git tag to make jester installed via `nimble install jester` work on latest nim ?

**Comment by dom96** [comment]
Fixed.
