### ISSUE TITLE
Sending files from private folder (await response.send)

### ISSUE THREAD

**Issue by ThomasTJdev** [dom96/jester#144]
Jester 0.3.0 does not support `response`, which I have used to send private files, e.g. profile pictures and images only available for users who are logged in.

In Jester's `TODO.md` it is noted that `Sending files: sendFile` is on the list, but it is marked as less important. Is there another way to achieve my goal to send files to the user, when the files are **not** placed in the `public/` folder?

**My current solution in Jester 0.2.0**
```nim
get "/secretimage/@filename":
  if userHasAccess():
    let filepath = "/private/files/" & @"filename"

    let ext = splitFile(filename).ext
    await response.sendHeaders(Http200, {"Content-Disposition": "", "Content-Type": "application/" & ext}.newStringTable())
    var file = openAsync(filepath, fmRead)
    var data = await file.read(4000)

    while data.len != 0:
      await response.client.send(data)
      data = await file.read(4000)
    file.close()
```

**Example from Jester 0.2.0**
```nim
get "/live":
  await response.sendHeaders()
  for i in 0 .. 10:
    await response.send("The number is: " & $i & "</br>")
    await sleepAsync(1000)
  response.client.close()
```

**Comment by dom96** [comment]
Implementing ``sendFile`` should be fairly trivial.

**Comment by ThomasTJdev** [comment]
You beat me to it ;). I am looking forward to test it in the weekend.
