### ISSUE TITLE
Top level exception handler

### ISSUE THREAD

**Issue by FedericoCeratto** [dom96/jester#147]
A hook to handle exceptions in routes would allow to do things like: redirect the traceback to log sinks other than stdout, format them in ways to make it easier to extract the traceback from logs, send alerts and so on.
The arguments could be the name/path of the route and the text of the traceback.

The hook could also return a value to instruct Jester to serve the traceback to the web client, or return 500 or a custom sorry page.

**Comment by dom96** [comment]
https://github.com/dom96/jester/blob/master/tests/alltest.nim#L138

Implemented in 0.3.0.
