### ISSUE TITLE
issue regarding macrocache on 0.3.0

### ISSUE THREAD

**Issue by leitu** [dom96/jester#148]
Hi, 
I'm just starting to play with nim. 

When I compiler with expamle.nim, if I'm using jester 0.3.0, it always said .nimble/pkgs/jester-0.3.0/jester.nim(5, 38) Error: cannot open 'macrocache'

compare with 0.2.1 and 0.3.0. macrocache seems new in 0.3.0. I didn't see macrocache is one of the package in the nim package.json. would you please give a hint?

Thanks

**Comment by leitu** [comment]
I see the reason in upstream nim. thanks

**Comment by rustomax** [comment]
What was the solution? I am getting this message: .nimble/pkgs/jester-0.4.1/jester.nim(5, 38) Error: cannot open 'macrocache'.

Nim Compiler Version 0.18.1 [MacOSX: amd64]
nimble v0.8.10 compiled at 2018-03-05 18:07:47

**Comment by rustomax** [comment]
Just did a fresh install on Ubuntu using choosenim - same result. What am I missing here?

**Comment by dom96** [comment]
``choosenim devel``?

**Comment by rustomax** [comment]
That's a great question. So, I did have `choosenim devel`, but apparently I messed up my `$PATH` so that it pointed to the nim version installed via Homebrew. I ended up completely cleaning up all instances of nim and reinstalled with `choosenim`. Now it's all working. Thanks!
