### ISSUE TITLE
error handler does not run in jester 0.4.0

### ISSUE THREAD

**Issue by teroz** [dom96/jester#150]
Am using jester 0.40 with nim devel channel on Ubuntu and have the contrived web app example below.
If I enter an unknown url (http://localhost:5000/meh) the 404 handler below doesn't run instead the handler from jester/private/errorpages.nim is the one that gets displayed
```
import jester

routes:
  get "/":
    resp h1("Hello world")
  error Http404:
    resp Http404, "Looks you took a wrong turn somewhere."

  error Exception:
    resp Http500, "Something bad happened: " & exception.msg'
```

**Comment by dom96** [comment]
That's odd. I do have a test for this which has been passing https://github.com/dom96/jester/blob/master/tests/tester.nim#L170

**Comment by teroz** [comment]
That works @dom96. In my example if I do add another handler say for 401 then the 404 one works. ie
my code now looks like so and it works
```
import jester

routes:
  get "/":
    resp "Hello"
    
  error Http404:
    resp error.data.code, "OK: " & $error.data.code
  
  error Http401:
    resp error.data.code, "OK: " & $error.data.code
  
  error Exception:
    resp Http500, "Something bad happened: " & exception.msg
```

**Comment by dom96** [comment]
Huh. That's an interesting bug.

**Comment by teroz** [comment]
Awesome
