### ISSUE TITLE
The routing in 0.4.0 leads to Http400 errors instead of Http404

### ISSUE THREAD

**Issue by PrimordialHelios** [dom96/jester#152]
I decided to set up a small app to start trying to learn jester ([source](https://bitbucket.org/PrimordialHelios/nim-app/src)). Using the latest version of Jester and the new `router` syntax, Jester is responding with an Http400 instead of an Http404 when a resource is requested that can't be found.

For instance, my routing looks something like this:

```nim
router v0Api:
    get "/add":
        resp "This is the add page"

router apiRouter:
    extend v0Api, "/v0"

routes:
    error Http404:
        resp Http404, "Looks you took a wrong turn somewhere."
    extend apiRouter, "/api"
    get "/":
        resp "test"
```

The `/api/v0/add` and `/` pages work just fine, but trying to request any resource that doesn't exist (such as `/foo`, `/api/bar`, etc.) returns Http400.

**Comment by PrimordialHelios** [comment]
This may not be related to the new router syntax. With bare minimum routing it still returns a 400 error instead of 404. The following is the bare minimum needed to reproduce.

```nim
import jester, asyncdispatch

routes:
    get "/":
        resp "test"

runForever()
```

**Comment by ThomasTJdev** [comment]
@PrimordialHelios, I can't reproduce the Http400 return. When using your code snippets, I get a 404 return as expected when requesting non existing pages.
But I can't the `error Http404` route to work.

```nim
curl -i -X GET http://127.0.0.1:5000/page/not/exists
HTTP/1.1 404 Not Found
Content-Length: 178
Server: HttpBeast
Date: Sun, 05 Aug 2018 14:06:15 GMT
Content-Type: text/html;charset=utf-8

<html xmlns="http://www.w3.org/1999/xhtml"><head><title>404 Not Found</title></head><body style="text-align: center;"><h1>404 Not Found</h1><hr/><p>Jester 0.4.0</p></body></html>
```

**Comment by ThomasTJdev** [comment]
In the snippet below, the 404 returns your custom message with 404 code. I haven't checked Jesters code to why this is happening, but appending the extra `error Http404:` or `error {Http401 .. Http408}:` fixes it.

```nim
import jester

router v0Api:
  get "/add":
      resp "This is the add page"

router apiRouter:
  extend v0Api, "/v0"

routes:
  error Http404:
      resp Http404, "Looks you took a wrong turn somewhere."
  extend apiRouter, "/api"
  get "/":
      resp "test"

  # Appended:
  error Http404: # or error {Http401 .. Http408}:
    discard
```

**Comment by PrimordialHelios** [comment]
Using the minimum example I posted, not only do I still get a 400 error. Using the example code you posted I also get a 400 error

    C:\Users\Taylor>curl -i -X GET http://127.0.0.1:5000/page/not/exists
    HTTP/1.1 400 Bad Request
    content-type: text/html;charset=utf-8
    Content-Length: 182
    
    <html xmlns="http://www.w3.org/1999/xhtml"><head><title>400 Bad Request</title></head><body style="text-align: center;"><h1>400 Bad Request</h1><hr/><p>Jester 0.4.0</p></body></html>

but I also sometimes get the entire program crashing with an error about awaiting a nil future ([pastebin](https://pastebin.com/Ukhyj2RL))

Are you developing on Windows? I'm starting to wonder if that's causing the issue.

**Comment by ThomasTJdev** [comment]
Strange.. What version of Jester are you using?

```bash
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-07-17
Copyright (c) 2006-2018 by Andreas Rumpf

4.17.11-arch1 - x86_64 GNU/Linux
```

**Comment by PrimordialHelios** [comment]
Jester version is 0.4.0
```
c:\msys64\home\Taylor\Programming\Git\nim-app>nim --version
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-07-27
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 8b638ae59991009d6b0b08af2bcf48c11a04eaa2
active boot switches: -d:release
```

**Comment by ThomasTJdev** [comment]
I have just finished compiling Nim devel and Jester 4.0 on Win10, and I can confirm, that the response is indeed 400 - not the expected 404.

All my tests fails with my first request which are responding with 200, and the error message is the same as the one in your [pastebin](https://pastebin.com/Ukhyj2RL).
All request to 404 pages does not crash the program but returns 400.

```bash
...
Exception message: Async procedure (processRequest) yielded `nil`, are you await'ing a `nil` Future?
Exception type: [AssertionError]
```

**Comment by dom96** [comment]
Hrm, I'm not sure it's asynchttpserver's problem. Probably the way jester uses it.

**Pro-tip:** You can force the use of ``asynchttpserver`` by compiling with: ``-d:useStdLib``

**Comment by PrimordialHelios** [comment]
Got a cross compiler set up and can reproduce the issue with with wine on linux, so I can test this if needed

It also seems manual routing doesn't have this issue

**Comment by AmadeusW** [comment]
I'm also running into this. Specifically, the same issue as in #169. 
Please let me know what I can do to help figure this one out, or to prototype a workaround. I'm new to nim so verbose instructions would be great!

**Comment by AmadeusW** [comment]
The issue still happens after building with `-d:useStdLib`

**Comment by PrimordialHelios** [comment]
I finally set up a cross-compile environment again, and compiled a windows binary. Running through wine, it runs fine, the issue is no longer present.

I'll try and set up a dev environment on windows tomorrow and test it out, but no promises. I won't close until we make sure that it runs fine on Windows, but progress has definitely been made!

**Comment by PrimordialHelios** [comment]
Curiouser and curiouser.

Cross compiling for windows and running via wine would give the same "400 bad request" bug. Despite that being fixed, compiling and running on real windows still has this bug.

@dom96 I know nothing about how Jester works under the hood, but is it possible that asynchttpserver is using something in the underlying windows API that has some form of errata that wine has fixed?

**Comment by PrimordialHelios** [comment]
I ran the Windows-compiled exe through wine, and the bug is present. So, this bug only appears when compiling on windows, not cross compiling.

Is there anything that happens differently when cross compiling for windows than when compiling directly on windows?

**Comment by PrimordialHelios** [comment]
@AmadeusW your issue might be stemming from here:

https://github.com/dom96/jester/blob/2c46b6de232d01d9c95f98772e6fb56092f206df/jester.nim#L303

**Comment by dom96** [comment]
@PrimordialHelios Thanks for looking into this. Indeed the bug is somewhere in that code, perhaps the reason you're seeing different results is that you've got `jester@#master` on your non-windows machine and `jester@0.2.1` on your Windows machine? That would mean that this is fixed in master

**Comment by PrimordialHelios** [comment]
That's probably exactly what the issue is. I'll try later tonight or early tomorrow to build with master on windows. If this is fixed in master, I'll track down the commit that fixed it, because now I'm interested in what the bug was :P

**Comment by PrimordialHelios** [comment]
I figured it out. The bug only happens on 32 bit builds. Using the i386 Windows build from choosenim results in the error, but building manually with a 64 bit msys2 install works fine.

So now we need to find out why this only happens in 32 bit.

**Comment by PrimordialHelios** [comment]
Final update: Using a manually built i386 compiler... works! It looks like the bug was either in the compiler or the standard library and was fixed somewhere recently. The `stable` compiler installed by choosenim has this bug, but apparently `nim@#master` doesn't.

**Comment by dom96** [comment]
Wow. What a bug, don't want to narrow it down to the commit in Nim? :)

**Comment by PrimordialHelios** [comment]
![Screenshot_20190508_143410](https://user-images.githubusercontent.com/8160403/57399008-61238500-719e-11e9-968e-b2e9f7d9953a.png)
I'm good thanks ;)

**Comment by dom96** [comment]
That's bisect is for ;)

**Comment by PrimordialHelios** [comment]
That's a nifty little command. I'll make some tea and run some tests and update when I find it.

**Comment by AmadeusW** [comment]
Awesome, thanks for looking into this PrimordialHelios. I haven't updated nim in a while, I'll be sure to use the x64 version

**Comment by PrimordialHelios** [comment]
@AmadeusW use the devel branch, it still isn't fixed in master.

**Comment by PrimordialHelios** [comment]
@dom96 Alright, according to git bisect, this is the first nim commit that doesn't have the issue: ce9815b. `git branch --contains ce9815b` confirms that the commit is in devel, but not master.

Does that commit look like something that would affect this bug? I'm not familiar enough with Nim to figure it out myself, but if it's working with paths, I can see it fixing something.
