### ISSUE TITLE
"Jester is making jokes at http://0.0.0.0:5000" Is incorrect on Windows

### ISSUE THREAD

**Issue by PrimordialHelios** [dom96/jester#153]
Running an app with Jester 0.4.0 gives a hint output that Jester is bound to `http://0.0.0.0:5000`, but this is incorrect on Windows (Windows 10 in my case). For me, Jester is binding to `http://localhost:5000`, and doesn't serve anything on `http://0.0.0.0:5000`.

**Comment by Ivo-Balbaert** [comment]
Indeed I can confirm this. The correct address (at least on Windows) for localhost is 127.0.0.1, so this works: http://127.0.0.1:5000/ , probably also on other OS

**Comment by dom96** [comment]
0.0.0.0 means "all interfaces". It's just that Windows doesn't support this as an address, works for me on macOS though.

**Comment by PrimordialHelios** [comment]
IIRC Windows supports it as an address, it's just a different address from localhost

**Comment by dom96** [comment]
I'm happy to change this on Windows if `0.0.0.0` doesn't work in your browser.

**Comment by Araq** [comment]
You can even use ``browsers.nim`` to open the URL. More convenience for testing.

**Comment by dom96** [comment]
That would be an annoying feature (new tab each time I restart the server...)

**Comment by PrimordialHelios** [comment]
Sorry, I closed because I thought it was a bit of a nitpick :p

I think changing this for Windows would definitely be a good idea, it might cause some confusion for devs who don't know about the quirks of Windows.
