### ISSUE TITLE
I can not install jester 0.4.0. 

### ISSUE THREAD

**Issue by Nematjon1** [dom96/jester#154]
How I can solve this issue ?
Error: Unsatisfied dependency: nim (>= 0.18.1)
Please, can anyone tell me what to do ?

**Comment by dom96** [comment]
You need Nim ``devel``. Install it using [``choosenim``](https://github.com/dom96/choosenim#installation) (Easiest way) or via [other means](https://github.com/nim-lang/Nim#compiling).

If you use choosenim, once you install it just run ``choosenim devel``.
