### ISSUE TITLE
Manual routing doesn't work

### ISSUE THREAD

**Issue by PrimordialHelios** [dom96/jester#156]
Trying to compile the manual routing from example2 gives the error `main.nim(4, 18) Error: type mismatch: got <HttpHeaders> but expected 'Option[jester.RawHeaders]'`. I'm using the nim devel branch from choosenim and Jester v0.4.0

```
>nim --version
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-07-27
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 8b638ae59991009d6b0b08af2bcf48c11a04eaa2
active boot switches: -d:release
```

**Comment by DanielSokil** [comment]
I'm having the same issue.
