### ISSUE TITLE
Error: Unsatisfied dependency: nim (>= 0.18.1)

### ISSUE THREAD

**Issue by vanous** [dom96/jester#158]
Hi,
i am new to the nim ecosystem, so perhaps i am missing something... nim is available only as 0.18 (0.18.0-2 in Debian), so where is this 0.18.1 dependency coming from?

thank you

nimble install jester --verbose
    Reading official package list
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
     Trying https://github.com/nim-lang/packages/raw/master/packages.json
    Success Package list downloaded.
Downloading https://github.com/dom96/jester using git
    Cloning latest tagged version: v0.4.0
    Setting Nim stdlib prefix to /usr
    Setting Nim stdlib path to /usr/lib/nim
  Verifying dependencies for jester@0.4.0
     Error: Unsatisfied dependency: nim (>= 0.18.1)

**Comment by ThomasTJdev** [comment]
Hi @vanous 

Nim 0.18.1 is the devel version. You can install the devel version in 2 ways:

## Choosenim (easy)
*choosenim installs the Nim programming language from official downloads and sources, enabling you to easily switch between stable and development compilers.*

With choosenim you can easily switch between different Nim versions. You only need to install choosenim and run `choosenim devel`.

https://github.com/dom96/choosenim


## Compile Nim
Follow the guide from the Nim repo on how to compile Nim: https://github.com/nim-lang/Nim#compiling

**Comment by vanous** [comment]
Thank you. actually i did install devel through choosenim, but i think there is something missing to make the system know about it.

/home/vanous/.nimble/bin/nimble install jester
Downloading https://github.com/dom96/jester using git
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Nimble cannot use an older stdlib than the one it was compiled with.
        ...   Stdlib in '/usr/lib/nim' has version: 0.18.0.
        ...   Nimble needs at least: 0.18.1.
      Hint: You may be running a newer version of Nimble than you intended to. Run an older version of Nimble that is compatible with the stdlib that Nimble is attempting to use or set the environment variable NIM_LIB_PREFIX to where a different stdlib's `lib` directory is located as a workaround.See https://github.com/nim-lang/nimble#troubleshooting for more info.


So i presume i must export the NIM_LIB_PREFIX, but pointing NIM_LIB_PREFIX to where the dev bins are didn't help:

export NIM_LIB_PREFIX=/home/vanous/.nimble/bin/

but the result remains the same.

Here is what i do for pyenv in my .bashrc:

export PYENV_ROOT="$HOME/.pyenv"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
export PATH="$PYENV_ROOT/bin:$PATH"

thank you very much

**Comment by vanous** [comment]
ok, i have fixed by adding ./nimble/bin to my $PATH
thank you very much
