### ISSUE TITLE
`nimble test` fails

### ISSUE THREAD

**Issue by timotheecour** [dom96/jester#160]
/cc @dom96 

from a fresh clone, and using nim HEAD:

  Verifying dependencies for asynctools@0.1.0
  Compiling tests/alltest.nim (from package jester) using c backend
/private/tmp/d50/jester/tests/alltest.nim(3, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester.nim(9, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester/request.nim(80, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester/request.nim(101, 7) Warning: use stdlib; parseUrlQuery is deprecated [Deprecated]
        parseUrlQuery(req.body, result)
        ^
/private/tmp/d50/jester/tests/alltest.nim(3, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester.nim(80, 1) template/generic instantiation from here
/private/tmp/d50/jester/jester.nim(82, 14) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/system.nim(408, 10) Error: type mismatch: got <RawHeaders, nil>
but expected one of:

expression: headers == nil
    not (x == y)
           ^
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 256
        ... Command: "/Users/timothee/.nimble//bin/nim" c --noNimblePath --path:"/Users/timothee/.nimble/pkgs/httpbeast-0.2.1" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" "--hints:off"  "tests/alltest.nim"
Traceback (most recent call last)
/private/tmp/d50/jester/tests/tester.nim(205) tester
/Users/timothee/.nimble/pkgs/asynctools-0.1.0/asynctools/asyncproc.nim(216) processID
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: './tests/tester '
       Tip: 13 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 256
        ... Command: "/Users/timothee/.nimble//bin/nim" c --noNimblePath --path:"/Users/timothee/.nimble/pkgs/httpbeast-0.2.1" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" --path:"/Users/timothee/.nimble/pkgs/asynctools-0.1.0" "-r"  "tests/tester"
stack trace: (most recent call last)
private/tmp/d50/jester/jester.nimble(22) testTask
Users/timothee/git_clone/nim/Nim/lib/system/nimscript.nim(237) exec
/Users/timothee/git_clone/nim/Nim/lib/system/nimscript.nim(237, 7) Error: unhandled exception: FAILED: nimble c -y -r tests/tester

**Comment by dom96** [comment]
Fixed here https://github.com/dom96/jester/commit/8abdf6e04615cde364029f4c6a2a9771751d529a
