### ISSUE TITLE
jester.nimble refers to nim 18.0.1, but only 18.0.0 available

### ISSUE THREAD

**Issue by adilhasan** [dom96/jester#168]
Hello, I am following your excellent book Nim in Action and hit an unsatisfied dependency issue. It seems that the latest version is 0.18.0, but the jester.nimble file requires 0.18.1. Is it possible to use 0.18.0?
Many thanks, 
adil

**Comment by Xe** [comment]
Use git head nim.

**Comment by adilhasan** [comment]
ok, will do. 
Many thanks, adil

**Comment by lindem** [comment]
I am sorry to ask a (possibly dumb) question -- but what is the purpose of insisting on an unpublished version? Is there a feature jester cannot do without (obviously there is)? What is it?

I am learning this, please go easy on me ☺

**Comment by dom96** [comment]
> Is there a feature jester cannot do without (obviously there is)? What is it?

Yep. It's the new macro cache thing that Jester depends on. Mostly because I was too lazy to support 0.18.0 as well.

In any case, 0.19.0 has been released and Jester should work with it :)
