### ISSUE TITLE
RFC: Param handling

### ISSUE THREAD

**Issue by alehander42** [dom96/jester#172]
Currently, it seems the simplest way to match and use params in routes is

```nim
get "/games/@name":
  save(@"name")
```

It's nice one can use a shortcut, but `@<string>` looks very strange in a Nim program. 
I propose to directly make it a local variable: (or if it's equivalent to request.stuff["name"], a template).

so one can

```nim
get "/games/@name":
  save(name)
```

The only con might be that it can clash with a local name, but having a local `name` different than `@"name"` would be even more confusing

**Comment by dom96** [comment]
Sorry, but no. This is inspired by Sinatra and works well.

**Comment by alehander42** [comment]
AFAIK sinatra uses params["name"],  `@"name"` is definitely different. 
It still looks bizarre to me, I'll create some kind of DSL on top of get/post etc
