### ISSUE TITLE
RFC: Param types

### ISSUE THREAD

**Issue by alehander42** [dom96/jester#173]
Currently one needs to parse manually param values AFAIK

```nim
get "/game/@id":
  echo (@"id").parseInt
```

We can somehow hint at least the cases when it's a number or a flag.

Something like this seems sufficient

```nim
get "/game/@id:int":
  echo (@"id")
```

or

```nim
get "/game/@id" do (id: int): # I am not a huge fan, because we need to write id twice
  echo id
```

**Comment by dom96** [comment]
Again, no. Jester is somewhat dynamic by design, just like Sinatra.

**Comment by alehander42** [comment]
Well if a param can have different types (seriously, does this happen? at all?) one can always just use "@id" and parse it manually. It's optional "typing"

**Comment by dom96** [comment]
I don't really want to make the patterns in Jester more complicated, you're more than welcome to write your own router on top of Jester. If I wanted to add typing I would create a completely different syntax for it, hacking these types onto what we have now will just create a frankenstein.

**Comment by alehander42** [comment]
Ok, I will.
