### ISSUE TITLE
Subdomain routes?

### ISSUE THREAD

**Issue by alehander42** [dom96/jester#174]
It seems to me there is no subdomain info, at least in httpBeast I don't see a parser for it (or for host?).
Would it make sense support for a subdomain param to be added to routes?

**Comment by dom96** [comment]
I don't know a web framework that allows this, do you?

**Comment by alehander42** [comment]
Rails: https://guides.rubyonrails.org/routing.html#request-based-constraints
Flask: http://flask.pocoo.org/docs/1.0/api/#url-route-registrations
Laravel: https://laravel.com/docs/5.7/routing#route-group-sub-domain-routing

**Comment by alehander42** [comment]
For flask look at the table with args

**Comment by Epictek** [comment]
A work around for this might be to pass the subdomain as an argument using nginx?  Not an ideal method but should work.

https://stackoverflow.com/a/22774520

**Comment by dom96** [comment]
Yep. You can do that. I would personally use a different binary for each
subdomain and handle that via nginx.

**Comment by alehander42** [comment]
I can always use nginx indeed, but it would be nice to be able to use this feature in development env without that complicated setup. It's something that other miniframeworks(e.g. flask) already support, that's why I thought a PR for it might not be not an overkill.

Anyway, this should be an issue in the httpbeast repo I guess (even if Jester doesn't need this, it would be useful for other Nim frameworks)

**Comment by dom96** [comment]
You just check the "Host" header, httpbeast doesn't need anything in
addition to exposing the headers.

**Comment by alehander42** [comment]
Closing: I wrote my own mini-dsl on top of jester routes(reusing routes) for this

**Comment by UNIcodeX** [comment]
@alehander92 I'd be interested in seeing your solution. More so to learn from for other modifications to the Jester DSL.
