### ISSUE TITLE
Possible Issue With Service Hooks Example

### ISSUE THREAD

**Issue by PrimordialHelios** [dom96/jester#180]
The bottom of the readme provides an example of service hooks. However, testing with cURL I was unable to get it to work as-is. I eventually got it to work by replacing `parseJson(@"payload")` with `parseJson(request.body)`.
```nim
import jester, json

routes:
  post "/":
    var push = parseJson(@"payload")
    resp "I got some JSON: " & $push
```
Is this an issue with the example, or just with my testing?

**Comment by dom96** [comment]
Interesting. Seems GitHub changed its ways: https://developer.github.com/webhooks/configuring/

Please make a PR updating the readme :)

**Comment by PrimordialHelios** [comment]
I was actually using this with Bitbucket, but if it affects Github as well then I'll be more than willing to make a PR :)

**Comment by PrimordialHelios** [comment]
Well after some testing, it looks like my issues were just because of the differences between github and bitbucket's webhook payloads. Everything works fine with the code in the readme already :P
