### ISSUE TITLE
Speed comparison with httpserver

### ISSUE THREAD

**Issue by gabipurcaru** [dom96/jester#20]
I don't know how exactly this works behind the scenes, but it seems terribly slow at the moment, compared to a dumb httpserver. Here is the code tested, with `nim [file] c -r --checks:off --opt:speed >/dev/null`:

    import jester, asyncdispatch, htmlgen

    routes:
      const r = h1 "hello world"
      get "/":
        resp r

    runForever()

and

    import strutils, sockets, httpserver

    proc handleRequest(client: Socket, path, query: string): bool {.procvar.} =
      client.send("<h1>hello world</h1>")
      client.close

    run(handleRequest, Port(5000))

And here are the benchmarks for `ab -n10000 -c400 http://localhost:5000/`:

    # Jester
    Concurrency Level:      400
    Time taken for tests:   13.004 seconds
    Complete requests:      10000
    Failed requests:        0
    Total transferred:      840000 bytes
    HTML transferred:       200000 bytes
    Requests per second:    768.98 [#/sec] (mean)
    Time per request:       520.171 [ms] (mean)
    Time per request:       1.300 [ms] (mean, across all concurrent requests)
    Transfer rate:          63.08 [Kbytes/sec] received

    Connection Times (ms)
                  min  mean[+/-sd] median   max
    Connect:        0   18 227.7      0    3004
    Processing:    49   67 173.7     55   10387
    Waiting:        6   67 173.6     55   10387
    Total:         52   86 364.7     55   10387

    Percentage of the requests served within a certain time (ms)
      50%     55
      66%     56
      75%     57
      80%     58
      90%     60
      95%     62
      98%     79
      99%    129
     100%  10387 (longest request)

    # httpserver
    Concurrency Level:      400
    Time taken for tests:   0.438 seconds
    Complete requests:      10000
    Failed requests:        0
    Total transferred:      200000 bytes
    HTML transferred:       0 bytes
    Requests per second:    22855.89 [#/sec] (mean)
    Time per request:       17.501 [ms] (mean)
    Time per request:       0.044 [ms] (mean, across all concurrent requests)
    Transfer rate:          446.40 [Kbytes/sec] received

    Connection Times (ms)
                  min  mean[+/-sd] median   max
    Connect:        1    2   1.2      2      13
    Processing:     1    3   0.9      3       9
    Waiting:        1    3   0.8      3       7
    Total:          3    6   1.7      5      18

    Percentage of the requests served within a certain time (ms)
      50%      5
      66%      5
      75%      5
      80%      5
      90%      8
      95%      9
      98%     10
      99%     16
     100%     18 (longest request)

The mean time per request is 520ms vs 17ms, so a 30x slowdown. Now, I get that Jester is supposed to do much more than a dumb httpserver, but 30x seems way off for me. Do you know why this is happening or whether it's going to get better?

**Comment by dom96** [comment]
Jester uses asynchttpserver for its back-end and both Jester and asynchttpserver still need a lot of optimisation unfortunately. Httpserver is deprecated and uses blocking sockets

**Comment by dom96** [comment]
I've also just noticed that you're compiling with ``--opt:speed`` not ``-d:release``. I've tested the performance myself and it's satisfactory.
