### ISSUE TITLE
Can't install version 0.4.2

### ISSUE THREAD

**Issue by oz** [dom96/jester#205]
I tried to install the latest tagged release (0.4.2) but it looks like you forgot to update `jester.nimble` (and `jester.jesterVer` :smile:) before tagging.

When depending on `jester >= 0.4.2`, nimble complains:

```
$ nimble install --verbose jester@0.4.2
    Reading official package list
Downloading https://github.com/dom96/jester using git
    Cloning latest tagged version: v0.4.2
     Error: Downloaded package's version does not satisfy requested version range: wanted 0.4.2 got 0.4.1.
```

Is there another way to get that version?

**Comment by dom96** [comment]
Surprised no one else caught this in so many months ... released a new version to fix it.
