### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by narimiran** [dom96/jester#207]
When trying to run `nimble install jester`, I get:

```
Downloading https://github.com/dom96/jester using git
  Verifying dependencies for jester@0.4.3
 Installing httpbeast@>= 0.2.2
Downloading https://github.com/dom96/httpbeast using git
  Verifying dependencies for httpbeast@0.2.2
 Installing https://github.com/timotheecour/asynctools@#pr_fix_compilation
Downloading https://github.com/timotheecour/asynctools using git
       Tip: 8 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_7034/githubcom_timotheecourasynctools_#pr_fix_compilation/asynctools.nimble;
        ...   Reading as ini file failed with: 
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with: 
        ...     Invalid field: /tmp/nimble_7034/githubcom_timotheecourasynctools_.
```

cc @timotheecour

**Comment by dom96** [comment]
This looks like your Nimble is broken rather than the package possibly.

**Comment by narimiran** [comment]
> This looks like your Nimble is broken rather than the package possibly.

I can install other packages without any error.

**Comment by timotheecour** [comment]
https://github.com/cheatfate/asynctools/pull/18 has been merged in june, so https://github.com/dom96/httpbeast/blob/master/httpbeast.nimble could be updated to remove dependency on `requires "https://github.com/timotheecour/asynctools#pr_fix_compilation"` and use upstream asynctols instead

that being said, this did work for me (just tested it):
```
export NIMBLE_DIR=/tmp/nimble_temp
nimble install jester
```

**Comment by narimiran** [comment]
> This looks like your Nimble is broken rather than the package possibly.

You were right.

If somebody else has the same problem:

1. update your `koch`: `nim c -d:danger koch.nim`
2. use that `koch` to update `nimble`: `./koch nimble`
