### ISSUE TITLE
what is considered a devel version of nim?

### ISSUE THREAD

**Issue by abulka** [dom96/jester#214]
The jester readme says `# Note: Starting with Jester 0.3.0, a devel version of Nim is required.` What is considered a devel version of nim? Is having a late enough version of nim enough, or does num **have** to be built and run from from github? This sounds like an inconvenient limitation?

I am running `Nim Compiler Version 0.20.2 [MacOSX: amd64]` which was installed on Mac using `brew`. The main hello world example builds and runs, but I get 404 visiting `http://0.0.0.0:5000`.

**Comment by hokamoto** [comment]
Your issue does not seem to have something to do with the version requirement. Jester 0.4.3 works fine with Nim 0.20.2 on my Mac.

```
$ nim -v | grep Version
Nim Compiler Version 0.20.2 [MacOSX: amd64]

$ nimble list -i | grep jester
jester  [0.4.3]

$ nim c -r example.nim
[snip]
Hint: operation successful (84467 lines compiled; 2.702 sec total; 111.359MiB peakmem; Debug Build) [SuccessX]
Hint: /Users/hokamoto/NimProjects/example  [Exec]
INFO Jester is making jokes at http://0.0.0.0:5000
Starting 1 threads
DEBUG GET /
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
```
```
$ curl http://0.0.0.0:5000
<h1>Hello world</h1>
```

**Comment by abulka** [comment]
Thank you for the confirmation that I can use my existing nim!

I've discovered that I'm getting a 404 even when the jester server is not running, so maybe I've got something weird running on that port already.  How do I change the port?  When I tried adding:

```
settings:
    port = Port(5005)
```

I get ` Error: 'port' cannot be assigned to`

**Comment by hokamoto** [comment]
The below snippet worked for me.
```Nim
import htmlgen
import jester

settings:
  port = Port(5005)

routes:
  get "/":
    resp h1("Hello world")
```

**Comment by abulka** [comment]
Ah - that worked.  The `settings:` have to be declared before the routes, it seems.  Thanks!

**Comment by abulka** [comment]
P.S. Perhaps another port might be used as the default as 5000 seems to be reserved on Macs and possibly other platforms?
- https://github.com/aspnet/Hosting/issues/746
- http://www.networksorcery.com/enp/protocol/ip/ports05000.htm

**Comment by dom96** [comment]
Reserved for what? Pretty sure most ports will conflict with something.
