### ISSUE TITLE
Readme says that devel version is required?

### ISSUE THREAD

**Issue by yumaikas** [dom96/jester#217]
So, the readme says that a development version of the Nim compiler is required? Is that still current? If not, I'd be more than happy to open a PR updating the readme to clarify a specific version. 

The only reason I'm bringing this up is because Nim recently went 1.0, and Jester is one of Nim's flagship packages, so I'd like to help spruce it up for other newcomers. I'd like to start by bringing the Nim version requirements up to date (though eventually I'd like to contribute to the docs)

**Comment by Araq** [comment]
I'm pretty sure 1.0 works for jester.

**Comment by dom96** [comment]
yeah, this is outdated. PRs welcome.

**Comment by yumaikas** [comment]
Awesome! I'll try to get one in tonight then.
