### ISSUE TITLE
Binary File upload

### ISSUE THREAD

**Issue by TheAnonymous** [dom96/jester#22]
Hi, I'm trying to build a simple file upload with jester and it works with text files but when I upload a image the image is corrupted through ascii conversion.
Here my code:
```
import os, re, jester, asyncdispatch, htmlgen, asyncnet

routes:
  get "/":
    var html = ""
    for file in walkFiles("*.*"):
      html.add "<li>" & file & "</li>"
    html.add "<form action=\"upload\" method=\"post\"enctype=\"multipart/form-data\">"
    html.add "<input type=\"file\" name=\"file\"value=\"file\">"
    html.add "<input type=\"submit\" value=\"Submit\" name=\"submit\">"
    html.add "</form>" 
    resp(html)
    
  post "/upload":
    writeFile("test.png", request.formData["file"].body)
    resp(request.formData["file"].body)
runForever()
```
Is there a way to save it in binary? Also I'm not shure if the conversion happens while I save the file or while the file gets transmitted.

Greetings Jakob

**Comment by dom96** [comment]
Sorry it took me so long to look into this. There is something odd going on here, seems Nim is converting bytes in the string to something inappropriate.

**Comment by dom96** [comment]
It turned out it was a bug with the way that Jester was parsing the POST data.

**Comment by TheAnonymous** [comment]
Thanks a lot!
