### ISSUE TITLE
Whip?

### ISSUE THREAD

**Issue by TensorTom** [dom96/jester#222]
I know you have code merging from beast. What about https://github.com/mattaylor/whip ? Curious. Rather than rewrite the httpauth module (Which is not yet stable) functionality, I easily ported my jester code to python's aiohttp/web server module and threw in uvloop. Here are some numbers from a couple years ago: https://magic.io/blog/uvloop-blazing-fast-python-networking/ . Whip is obviously very competitive.

I'm wondering where you feel jester now sits in comparison to the py modules and thoughts on whip. Since I now have a site in both jester and aiohttp, I'll run https://github.com/wg/wrk on them.

**Comment by TensorTom** [comment]
aiohttp + uvloop:

```
Running 30s test @ http://127.0.0.1:1337/
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   115.55ms    6.35ms 382.19ms   86.71%
    Req/Sec   294.35     75.05   363.00     81.38%
  102326 requests in 30.05s, 483.44MB read
Requests/sec:   3405.15
Transfer/sec:     16.09MB
```

jester:

```
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   311.70ms   68.26ms   1.93s    64.43%
    Req/Sec    87.82     70.86   303.00     70.54%
  28730 requests in 30.04s, 156.42MB read
  Socket errors: connect 0, read 0, write 0, timeout 182
Requests/sec:    956.52
Transfer/sec:      5.21MB
```

**Comment by TensorTom** [comment]
Just remembered jester was compiled there in single thread because of the httpauth thing. Will correct.

**Comment by TensorTom** [comment]
Edited benchmark above. The same site was used. Jester was compiled with threads on with release build of course. Moving my site back to jester lol.

**Comment by TensorTom** [comment]
Updated with whip

**Comment by dom96** [comment]
Jester is fast enough for my use cases. If you like Whip's performance feel free to use it :)
