### ISSUE TITLE
No logging with `--threads:on` compiling

### ISSUE THREAD

**Issue by jiro4989** [dom96/jester#223]
## Normal case

I compiled and run this code.

```nim
import htmlgen
import jester

routes:
  get "/":
    resp h1("Hello world")
```

```bash
$ nim c main.nim
$ ./main
```

And send request.

```bash
$ curl http://localhost:5000
<h1>Hello world</h1>
```

Logging.

```bash
$ ./main
INFO Jester is making jokes at http://0.0.0.0:5000
Starting 1 threads
DEBUG GET /
DEBUG   200 OK {"content-type": @["text/html;charset=utf-8"]}
```

## Problem case 1

No logging with `--threads:on` compiling

```bash
$ nim c --threads:on main.nim
$ ./main
```

Send request.

```bash
$ curl http://localhost:5000
<h1>Hello world</h1>
```

No logging.

```bash
$ ./main
INFO Jester is making jokes at http://0.0.0.0:5000
Starting 4 threads
Listening on port 5000
# NO debug log
```

## Problem case 2

Add logging code.

```nim
import htmlgen
import jester

import logging # Add

routes:
  get "/":
    info "GET /" # Add
    resp h1("Hello world")
```

```bash
$ nim c --threads:on main.nim
$ ./main
```

Send request.

```bash
$ curl http://localhost:5000
<h1>Hello world</h1>
```

No request logging.

```bash
$ ./main
INFO Jester is making jokes at http://0.0.0.0:5000
Starting 4 threads
Listening on port 5000
# NO debug log
# NO info log
```

**Comment by jiro4989** [comment]
Need log setting when creating threads?
https://nim-lang.org/docs/logging.html#basic-usage-notes-when-using-multiple-threads

**Comment by xbello** [comment]
I'd bet that this is a problem with [httpbeast](https://github.com/dom96/httpbeast), the jester backend multithreaded server. If you compile with:

`$ nim c --threads:on -d:useStdLib main.nim`

The logging works.

And for example, this code (taken from the httpbeast examples, and adding logging) works correctly but doesn't log:

    import asyncdispatch
    import logging
    import options
    import asyncdispatch

    import httpbeast

    var logger = newConsoleLogger(fmtStr="[$time] - $levelname: ")
    addHandler(logger)

    proc onRequest(req: Request): Future[void] =
      if req.httpMethod == some(HttpGet):
        case req.path.get()
        of "/":
          info("INFO Hello World")
          req.send("Hello World")
        else:
          req.send(Http404)

    run(onRequest)
