### ISSUE TITLE
Using router macro inside of a closure produces nothing but HTTP 400 errors

### ISSUE THREAD

**Issue by 3n-k1** [dom96/jester#229]
I want to pass an a configuration object to my routes as well as specify a custom port, so I'm using a closure around the router macro. While this does compile and run (on the correct port no less), all requests lead to an Http400 error page.

Minimal example:

```nim
import jester

proc configRoutes() =
  router myrouter:
    get "/":
      resp "foo"

configRoutes()
var settings = newSettings(port=Port(8000))
var myjester = initJester(settings=settings)
myjester.serve()
```

**Comment by 3n-k1** [comment]
Using the `settings` macro inside the closure fixes this. The following code works:

```nim
import jester

proc configRoutes() =
  settings:
    port = Port(8000)
  routes:
    get "/":
      resp "foo"

configRoutes()
runForever()
```

I'm leaving this open because I'm not sure if this is intended behavior or not.

**Comment by dom96** [comment]
This isn't a bug, you need to pass your router to Jester in your first example: `initJester(myRouter, ...)` (of course, you'll probably need to define it outside the proc...

See the overloads of ``initJester`` here: https://github.com/dom96/jester/blob/master/jester.nim#L441-L461

**Comment by 3n-k1** [comment]
> (of course, you'll probably need to define it outside the proc...

Oof, this may be the dumbest mistake I've made. Thanks for letting me know!

**Comment by 3n-k1** [comment]
Hmm, I tried defining the router outside the closure. It compiles and runs, but segfaults when I send a request:
```nim
import jester

proc configRoutes() =
  router myrouter:
    get "/":
      resp "foo"

var myrouter: MatchProc

configRoutes()
var settings = newSettings(port=Port(8000))
var myjester = initJester(myrouter, settings=settings)
myjester.serve()
```
```
INFO Jester is making jokes at http://0.0.0.0:8000
Starting 1 threads
DEBUG GET /
Traceback (most recent call last)
/home/tay/test.nim(13)   test
/home/tay/.nimble/pkgs/jester-0.4.3/jester.nim(482) serve
/home/tay/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(423) run
/home/tay/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(287) eventLoop
/home/tay/.nimble/pkgs/httpbeast-0.2.2/httpbeast.nim(219) processEvents
/home/tay/.nimble/pkgs/jester-0.4.3/jester.nim(485) :anonymous
/home/tay/.nimble/pkgs/jester-0.4.3/jester.nim(386) handleRequest
/home/tay/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncmacro.nim(313) dispatch
/home/tay/.choosenim/toolchains/nim-1.0.4/lib/pure/asyncmacro.nim(34) dispatchNimAsyncContinue
/home/tay/.nimble/pkgs/jester-0.4.3/jester.nim(285) dispatchIter
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/home/tay/test '
```
Am I doing something wrong?

**Comment by dom96** [comment]
That's very odd, not sure what's wrong here. Can you investigate? :)

**Comment by 3n-k1** [comment]
I'll do my best, but it might take me a little while. As of right now, I can at least confirm that this is not an issue with httpbeast, but that's about it :P

**Comment by 3n-k1** [comment]
Alright, I've found part of the issue. It resides [here](https://github.com/dom96/jester/blob/master/jester.nim#L295). In the example given, `matcher.asyncProc` is nil, leading to the segfault when trying to access it. Also, in the above example, `myrouter` is still `nil` after calling `configRoutes`.
[Here](https://play.nim-lang.org/#ix=26fx) is the code generated by the router macro expansion.
I'm not quite sure what the issue is though :/

**Comment by 3n-k1** [comment]
The rabbit hole deepens. The following code works perfectly:
```nim
import jester

proc configRoutes(): proc (request: Request): ResponseData{.noSideEffect, gcsafe, locks: 0.} =
  router myrouter:
    get "/":
      resp "foo"
  return myrouter

var myrouter = configRoutes()
var settings = newSettings(port=Port(8000))
var myjester = initJester(myrouter, settings=settings)
myjester.serve()
```
It looks like a few changes are introduced to the macro. I'm not super experienced in Nim, but the procs generated should probably be marked with the `closure` pragma, and the macro should implicitly return the following (horrible, horrible) tuple:
```nim
tuple[router: proc (request: Request): ResponseData{.noSideEffect, gcsafe, locks: 0.}, handler: proc (request: Request; error: RouteError): Future[ResponseData] {.gcsafe.}]
```
Or you could just document the edge case, whichever works :P
