### ISSUE TITLE
walkDirRec

### ISSUE THREAD

**Issue by TheAnonymous** [dom96/jester#23]
Hi the walkDirRec function doesn't seem to work in a GET request.
If I do this
```
import os, re, jester, asyncdispatch, htmlgen, asyncnet


routes:
  
  get "/":
    var html = ""
    html.add "<form action=\"upload\" method=\"post\"enctype=\"multipart/form-data\">"
    html.add "<input type=\"file\" name=\"file\"value=\"file\">"
    html.add "<input type=\"submit\" value=\"Submit\" name=\"submit\">"
    html.add "</form>"
    html.add "<h3>Folder</h3>"
    for file in walkDirRec("./"):
      html.add "<li><a href=\"" &file & "\">" & file & "</li>"
    resp(html)

runForever()

```
i get

```
/nimcache/posix.c:103:18: error: invalid application of 'sizeof' to an incomplete type 'DIR' (aka 'struct __dirstream')
NTI103214.size = sizeof(DIR);
                 ^     ~~~~~
/usr/include/dirent.h:127:16: note: forward declaration of 'struct __dirstream'
typedef struct __dirstream DIR;
               ^
1 error generated.
Error: execution of an external program failed
```

Am I doing something wrong or is this a bug?

Greetings Jakob

**Comment by dom96** [comment]
This is a Nim compiler bug. Can you compile other code?

**Comment by TheAnonymous** [comment]
Yes if I do 

```
    for file in walkFiles("*.*"):
      html.add "<li><a href=\"" &file & "\">" & file & "</li>"
    resp(html)

```
everything is fine. Also when I do a simple

```
import os, re
for f in walkDirRec("./"):
  echo f
```
it works fine. So it seems like Jester has something to do with it.
FYI nim -v is

```
Nim Compiler Version 0.10.2 (2014-12-31) [Linux: amd64]
```
if I use Clang or GCC doesnt matter both throw this error.

Greetings Jakob

**Comment by dom96** [comment]
This is definitely a Nim compiler bug. Could you try the latest compiler from devel? (0.10.3)

If it still doesn't work then report it on Nim's repo.

**Comment by TheAnonymous** [comment]
OK i tested it with the latest devel version and it also failed.
So I made a issue at the Nim repo https://github.com/Araq/Nim/issues/2116
Thanks for your fast reply!

Greetings Jakob
