### ISSUE TITLE
Any plan on publishing a Book on Jester?

### ISSUE THREAD

**Issue by JohnAD** [dom96/jester#232]
@dom96 

I'm just rolling this idea around in my head. Writing a full technical book on web development in Nim, covering jester, moustachu, ndb, norm, etc. (Maybe even karax) would be fun. Perhaps a chapter or two on Docker hosting.

I know the Nim in Action book introduces Jester, but it is not as exhaustive as I'm thinking.

I figured I'd ask before I start scratching out a draft. If you already have a plan on something similar, I'll back off.

**Comment by dom96** [comment]
Definitely don't have a plan. A book on Jester would be awesome, please feel free to start a draft (pro-tip: AsciiDoc is best).

**Comment by JohnAD** [comment]
Ok!

I'll give it serious consideration. I have a tiny publishing company with three books published already. But this would be the first book I'd publish that I would be authoring myself. I suspect it would be 200+ hrs of work, so I'll be thinking about it for a while first.
