### ISSUE TITLE
Thoughts about Jester and practical header handling

### ISSUE THREAD

**Issue by oderwat** [dom96/jester#24]
## Thoughts about Jester and practical header handling

I looked into the code and think that I would like to contribute some changes to add functionalities based around headers. 

But at first: I am not sure if that is really in the scope of Jester (and where to stop). I don't know "sinatra". I just develop our companies own framework since 1997 and it is opinionated but very flexible about how stuff works. It evolved 18 years and as such is still very compact and backward compatible to the version from 10 years ago. Which I mention because "the scope" of Jester could be equal to that, which is based on practical experience with many mostly database focused projects.
### Some Targets

My main targets would be extending the current code in a way that headers are not something which is handled "just in the end" of handling a request. 

I also believe that "status code" has not really a lot to do with the content you send. Many "error code" responses could have a nice HTML page or for example json content. 

As another example: There are a lot of different and meaningful ways of redirection besides 303 so this needs to be a parameter (with a sensible default).

Content-Type... well I love to server images, csv, pdf, json dynamically generated through the framework. HTML is just one thing which will profit from extended header handling (for example it is really nice to have e-tags to decide if an image needs to be recreated).
### Header handling

Basically headers should be "collected" throughout the processing and there should be some practicable functionality implemented around HTTP "caching" (which does not cache anything). Disabling the default header handling should be optional, as there are always sensitive defaults!
#### content related
- content-type is invaluable  (should just "default" to text/html)
- compression gzip and deflate come to mind
- languages / encodings and other stuff maybe later...
#### caching related
- if-modified-since: should by default work for static sources
- last-modified: should be send per default for everything
- expires: should be easily to set (like expires in timeframe or at given time)
- A "nocache" mode (absolutely no!) could be implemented as some "magic" headers
- e-tags: could be available with some nearly "raw" helpers and as functions about the content response. Later would not safe time for computing of the answer but skips the transfer (useful to safe bandwith)
### Conclusion

If those changes are in the scope for Jester I can try to improve the headers and some other stuff. I am not sure how much time I can invest because I can't move our projects to Jester and Nim. Mostly because our codebase is just to big. But there may be a way to "integrate" stuff which I don't see right now. Besides that I may find a project which could be based on jester in the near future.

**Comment by dom96** [comment]
> My main targets would be extending the current code in a way that headers are not something which is handled "just in the end" of handling a request.

I'm not sure what you mean by this. How are headers only handled at the end of the request? You can set them at any time in your route.

> I also believe that "status code" has not really a lot to do with the content you send. Many "error code" responses could have a nice HTML page or for example json content. 

Are you referring to the ``resp`` templates? Again, you can set the status code outside of that via https://github.com/dom96/jester/blob/master/jester.nim#L353.

> As another example: There are a lot of different and meaningful ways of redirection besides 303 so this needs to be a parameter (with a sensible default).

Agree on this point.

> If those changes are in the scope for Jester I can try to improve the headers and some other stuff. I am not sure how much time I can invest because I can't move our projects to Jester and Nim.

Caching certainly is in Jester's scope.

**Comment by oderwat** [comment]
Well I have no experience with Jester and just glanced over the code.

I found "sendStaticIfExists()" (the reason why I looked in the first place) which (seems to) ignore all headers. I saw something like that for the redirect and the server error page. And there are four "sendHeaders()" procs but only one is actually taking headers as parameter. I know see that they are probably meant for sending raw content "myself". Still they could handle stuff like etags or ifmodified "before" I send my data. But this maybe just gave me a wrong impression.

Besides that: I am sure I could do anything with current jester if I handle everything myself. Thats why I asked about how much the framework should prepare. I scrolled through the "sinatra" code and I think I saw there what I kinda miss here. Which would make sense considering that Jester is not done yet!

In general I don't talk about individual headers a user would set for his "special stuff" but about the headers the framework would handle automatically. Think of the cookies.

I actually mean that the respective headers should be auto generated (as late as possible) based on features which are activated earlier in the process.

Lets say I want to enable compression for "every content" or I want to use "if-modified-since" and as such would always generate "last-modified" headers.

These should be handled inside or "near" to statusContent(). My framework has some step which generates the needed headers just before calling something similar. 

statusContent() itself could then handle the transparent compression (if enabled or 'still' enabled), which would create new headers.

There could also be a "checkETags" feature which in (or near) to statusContent() checks if a resending of the resource is desired .. or just says: not modified.

Or let me set "expire" for a group of files / (static) route and I would say "expire this in 10 minutes". And the framework will generate the headers I need for that. Similar to an Apache config, where you say: expire this like that...

Same with "I want to check for if-modified" and the framework would parse the header and short circuits the serving of a static resource.

About the Status code... I think that was a wrong impression I saw the "halt" and 303 and static 404 without sending content. I would not send "404" without a content in most of my sites. Not sure how that all plays out in the end.

I may not understand some concepts followed yet and I will try some Jester / Forum myself and come back for discussion before I mess anything up!

**Comment by dom96** [comment]
> I may not understand some concepts followed yet and I will try some Jester / Forum myself and come back for discussion before I mess anything up!

Yes, please try it out first. What you talk about should be possible. Would be awesome if you showed me some example code and told me what you expect it to do.

**Comment by oderwat** [comment]
Yeah. I will create a branch with some modifications to Jester. Let's see how that works out!

**Comment by dom96** [comment]
Awesome :)

**Comment by dom96** [comment]
Any news on this?
