### ISSUE TITLE
Cannot open the documentation

### ISSUE THREAD

**Issue by zolomatok** [dom96/jester#256]
👋

Running `nim doc jester.nim` (or `nim doc jester`) gives me:

```nim
Hint: used config file '/Users/zolo/.choosenim/toolchains/nim-1.2.6/config/nim.cfg' [Conf]
Hint: used config file '/Users/zolo/.choosenim/toolchains/nim-1.2.6/config/nimdoc.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: jester [Processing]
Error: cannot open 'jester.nim'
```

Halp please.

**Comment by C-NERD** [comment]
navigate to the jester directory which is present in the nimble pkgs directory the full path should look something like this
`/home/user/.nimble/pkgs/jester-0.5.0/`

inside this directory you'll find the jester.nim file, so open a terminal in the directory and run
`nim doc jester`

**Comment by dom96** [comment]
You can also access docs here https://nimble.directory/docs/jester/jester.html
