### ISSUE TITLE
Conditions don't work

### ISSUE THREAD

**Issue by zolomatok** [dom96/jester#259]
The example given in the _README_ on the use of `cond`s don't work. 

```nim
routes:
  get "/@name":
    cond @"name" != "daniel"
    # ``cond`` will pass execution to the next matching route if @"name" is not
    # "daniel".
    resp "Correct, my name is daniel."

  get "/@name":
    # This will be the next route that is matched.
    resp "No, that's not my name."
```

This will always resolve to `Correct, my name is daniel`, even if you visit `localhost:500/duke`

_**Jester 0.4.3**_

**Comment by oal** [comment]
Conditions work fine in 0.5.0, and it differentiates between the two. But it should be `cond @"name" == "daniel"` for the first route. Currently it says "Correct, my name is daniel" when you go to anything but `/daniel`, and "No that's not my name" for `/daniel`.
