### ISSUE TITLE
How do I have a Jester "make jokes" on anything other then localhost.

### ISSUE THREAD

**Issue by WilliamBehrens** [dom96/jester#272]
I can't seem to find this documented anywhere but I'm trying to deploy a website with Jester to ipfs but to start I'm just trying to figure out how to start it on any other ip than localhost.

**Comment by xflywind** [comment]
see
https://github.com/nim-lang/nimforum/blob/master/setup.md#http-server

**Comment by WilliamBehrens** [comment]
@xflywind That doesn't really explain much, that says how to set an instance of NimForum with nginx

**Comment by WilliamBehrens** [comment]
I figured it out, you have to add this in one of your .nim files.
```
settings:
       port = Port(6969)
       bindAddr = "127.0.0.1"
```
