### ISSUE TITLE
double log output when using httpbeast

### ISSUE THREAD

**Issue by niv** [dom96/jester#286]
* Run jester with httpbeast
* Have custom logging already set up
* HttpBeast adds a second logger (passed through settings/initSettings/...) with no way to dodge this short of rewriting the whole serve*(Jester) function.
* This results in all logging output on stdout being duplicated

**Comment by ThomasTJdev** [comment]
I agree. It would be nice to be able to specify the logging. For now I use something like this:
```nim
if logging.getHandlers().len() > 0:
  for logger in getHandlers():
    logger.fmtStr = "[$datetime] - $levelname: "
    logger.levelThreshold = (when defined(release): lvlInfo else: lvlAll)
```

**Comment by ohPaco** [comment]
@ThomasTJdev would like to see your changes for the fix, had you closed the PR?

**Comment by ThomasTJdev** [comment]
@ohPaco I have not started on it yet. I would prefer to have dom96's thoughts on a preferable solution before starting.

**Comment by ohPaco** [comment]
@ThomasTJdev understood. @dom96 would you be able to comment on this issue?

**Comment by dom96** [comment]
I'm not sure what options there are. I would need to have a look to know. If you guys had a look and have some ideas let me know and we can discuss which one would be best.

**Comment by ohPaco** [comment]
> I'm not sure what options there are. I would need to have a look to know. If you guys had a look and have some ideas let me know and we can discuss which one would be best.

@ThomasTJdev having looked into the issue, do you have any ideas?
