### ISSUE TITLE
Moustachu lib for your views

### ISSUE THREAD

**Issue by jpcweb** [dom96/jester#29]
I'm trying your framework with the moustachu lib and a html file and it's cool.
Indeed, moustachu is an implementation of mustach that allow you to pass parameters on rendering.
Furthermore the developers could use javascript or css (for exemple) into the rendering file.

Sorry for my english

**Comment by dom96** [comment]
So what do you suggest? That Jester supports Mustache natively?

**Comment by jpcweb** [comment]
Yes, Exactly !

**Comment by jefflunt** [comment]
What need would this address, besides convenience?

**Comment by dom96** [comment]
I think this should be a separate lib not included in Jester.
