### ISSUE TITLE
development on windows (httpbeast)

### ISSUE THREAD

**Issue by severak** [dom96/jester#298]
I work on [map rendering server](https://github.com/severak/lunarender3) which I want to run both on windows and linux. My main development machine is on windows but finished product will be run mostly on linux.

I ran into [some issues](https://forum.nim-lang.org/t/9222) with dependencies which I solved using `nimble lock` functionality. However on linux it did not want to compile as httpbeast was missing in `nimble.lock` file. I solved this using `-d:useStdLib` during build.

I have two questions:

- It's safe to not use httpbeast on linux? What functionality will be lost?
- If it's better to use it, how to include it on `nimble.lock` file if it's not used on windows?

**Comment by dom96** [comment]
> However on linux it did not want to compile as httpbeast was missing in nimble.lock file

Huh, that sounds like a lock file limitation that needs to be resolved. HttpBeast is a dependency of Jester only on non-Windows.

It's safe to not use httpbeast on Linux, but you will lose the performance advantage of utilising it.
