### ISSUE TITLE
finally block getting called twice?

### ISSUE THREAD

**Issue by sdmcallister** [dom96/jester#301]
In my terminal I see the following, but I would expect finally block to only be called once.

```
DEBUG GET /
trying
exception caught
finally block
finally block
```
MWE:
```
import jester

routes:
  get "/":
    try:
      echo "trying"
      raise
      resp "never seen"
    except:
      echo "exception caught"
      resp "exception block"
    finally:
      echo "finally block"
```

**Comment by dom96** [comment]
Can you try this outside jester (for example in an async proc) and see if it's the same? Just to ensure this is a jester-specific issue

**Comment by sdmcallister** [comment]
@dom96 Thanks!

If you mean some thing like what is below, the following code works as expected with only 1 finally block. 

```
import asyncdispatch

proc tryFinally(){.async.} =
  try:
    echo "trying"
    raise
  except:
    echo "exception caught"
  finally:
    echo "finally block"

waitFor tryFinally()
```

**Comment by dom96** [comment]
Looks like this is indeed a Nim bug. Jester uses `break` to break out of routes, adding a `break` in the except block reproduces this.

```nim
import asyncdispatch

proc tryFinally(){.async.} =
  try:
    echo "trying"
    raise
  except:
    echo "exception caught"
    break
  finally:
    echo "finally block"

waitFor tryFinally()
```
