### ISSUE TITLE
The jester.nimble file needs to be updated for v0.6.0

### ISSUE THREAD

**Issue by jfilby** [dom96/jester#314]
Right now Nimble won't install v0.6.0 because jester.nimble needs to be updated.

**Comment by ThomasTJdev** [comment]
Both the nimble file and the inline version number:
https://github.com/dom96/jester/blob/eac5e183485f2bc8cca83959869cbad23abebadb/jester.nim#L86

**Comment by dom96** [comment]
Classic mistake :)
