### ISSUE TITLE
Paths should be de-escaped before static serve

### ISSUE THREAD

**Issue by ozra** [dom96/jester#36]
When serving statically, say URL "foo%20bar.file", it should look for "foo bar.file" in filesystem.

**Comment by TheAnonymous** [comment]
Hi I had the same problem and wrote this
```nim
proc stringToUri(input: string): string =
    var result = input.replace(re"\(", "%28")
    result = result.replace(re"%", "%25")
    result = result.replace(re"\s", "%20")
    result = result.replace(re"\)", "%29")
    result = result.replace(re"\,", "%2C")
    result = result.replace(re"&", "%26")
    result
 
proc uriToString(input: string): string =
    var result = input.replace("%28", "(")
    result = result.replace("%20", " ")
    result = result.replace("%29", ")")
    result = result.replace("%2C", ",")
    result = result.replace("%26", "&")
    result = result.replace("%25", "%")
    result

```
Of course this is [not complete] (http://www.w3schools.com/tags/ref_urlencode.asp) nor good coding style but it may helps so...

**Comment by ozra** [comment]
@TheAnonymous I thought there already were complete functions for esc/unesc - just a matter of inserting the call at a reasonable place?

**Comment by TheAnonymous** [comment]
@ozra Well I searched for it but didn't found anything. IMHO such a thing should be in the [uri lib](http://nim-lang.org/docs/uri.html#parseUri,string,Uri).

**Comment by ozra** [comment]
In pure lib "cgi", `decodeUrl()`

**Comment by ozra** [comment]
@TheAnonymous - yeah you're right, it really should be in the uri lib!

**Comment by TheAnonymous** [comment]
@ozra Thanks a lot!
