### ISSUE TITLE
"?" symbol

### ISSUE THREAD

**Issue by luntik2012** [dom96/jester#38]
I cannot route like this

post "something?action=ololo":

because \? is not valid escape sequence.
Triple string are not working also.
I looked at patterns.nim and it seems that it is really impossible to route something
like that.

**Comment by Xe** [comment]
Route to `something`, [params in the Request object](https://github.com/dom96/jester#request-object) will have the `action`.

**Comment by luntik2012** [comment]
thank you. i don't know, how to close issue
