### ISSUE TITLE
Problem with devel version of Nim

### ISSUE THREAD

**Issue by Peter2121** [dom96/jester#43]
It seems that Jester does not work with the devel version of nim (pulled from devel branch of github). Trying to start example (from readme.md of Jester) I got:
Original stack trace in serve:
Traceback (most recent call last)
macros.nim(309)          example
jester.nim(326)          serve
asyncdispatch.nim(1225)  serve
asyncdispatch.nim(1212)  cb
asynchttpserver.nim(254) serveIter
asyncnet.nim(443)        bindAddr
rawsockets.nim(210)      getAddrInfo
os.nim(280)              raiseOSError

Continuing...
Traceback (most recent call last)
macros.nim(309)          example
jester.nim(326)          serve
asyncdispatch.nim(282)   asyncCheck
asyncdispatch.nim(224)   callback=
asyncdispatch.nim(286)   :anonymous
Error: unhandled exception: Invalid value for ai_flags No such file or directory [Exception]

I'm on FreeBSD 10.1 x64, Jester is reinstalled using nimble - no changes.

**Comment by dom96** [comment]
Has it worked previously? I never tested it on FreeBSD.

**Comment by Peter2121** [comment]
No problems with Jester compiled by master version of nim (11.2), but I have some troubles with js objects on 11.2:
http://forum.nim-lang.org/t/1583

**Comment by dom96** [comment]
I shall look into it, thank you for the bug report!

**Comment by PMunch** [comment]
This is probably not the case anymore. A lot has changed since 0.11.2

**Comment by dom96** [comment]
Yeah, going to close this. Reopen if still an issue.
