### ISSUE TITLE
Request params persist after POST request

### ISSUE THREAD

**Issue by flyx** [dom96/jester#45]
test code:

```nim
import jester, asyncdispatch

routes:
    get "/":
        let foo = $request.params
        echo foo
        resp """<form method=post action=/foo><input type=text name=bla><input type=submit value=.></form>"""
    post "/foo":
        let foo = $request.params
        echo foo
        resp """<p>Done. <a href="/">back</a></p>"""

runForever()
```

Steps to reproduce:

 1. open `/` in the browser
 2. enter something in the input field and press the button
 3. click `back`
 4. in the log, you will see that the GET request to `/` still gets the POST parameter of `/foo`.

**Comment by dom96** [comment]
Could this be something that the web browser does?

**Comment by flyx** [comment]
The browser could not possibly send POST data with a GET request. If it'd send the data as GET parameters, I'd see them in the URL bar (or at least with my browser debugging tools).

If I add a GET parameter to the `back` link like this: `<a href="/?foo=bar">`, I have both the POST and the GET parameter in `request.params` afterwards.

Here's jesters complete output for this case:

```
INFO Jester is making jokes at http://localhost:5000
DEBUG get /
{:}
DEBUG   200 OK {Content-Length: 90, Content-Type: text/html}
DEBUG post /foo
{bla: bli}
DEBUG   200 OK {Content-Length: 41, Content-Type: text/html}
DEBUG get /
{foo: bar, bla: bli}
DEBUG   200 OK {Content-Length: 90, Content-Type: text/html}
```
