### ISSUE TITLE
runtime error on windows x64 system

### ISSUE THREAD

**Issue by rogercloud** [dom96/jester#46]
Error:
```
could not load: pcre.dll
Error: execution of an external program failed
```

I have pcre64.dll in c:/Nim/bin/ directory, link this one should work.

**Comment by rogercloud** [comment]
Works with latest devel NIM, but not 0.11.2.

**Comment by dom96** [comment]
The DLL naming has changed 0.11.2 uses pcre.dll and devel uses pcre<yourarch>.dll
