### ISSUE TITLE
Error building project using jester with latest nim

### ISSUE THREAD

**Issue by luntik2012** [dom96/jester#55]
Nim Compiler Version 0.**13**.1 (2016-02-24) [Linux: amd64]
jester-0.1.0

My error is 

> radio_server.nim(**36**, 1) template/generic instantiation from here
lib/core/macros.nim(316, 70) template/generic instantiation from here
lib/pure/asyncdispatch.nim(1254, 8) Error: 'cb' is not GC-safe as it accesses 'nameIterVar' which is a global using GC'ed memory

radio_server.nim is my own file which contains this string N**36**
`routes:`

I compiled with jester-0.1.0 and nim 0.**12**.1.
I didn't change my code since previous nim version.

Thank you

**Comment by luntik2012** [comment]
it compiles when switching --threads:off it seems

**Comment by dom96** [comment]
Good question.

**Comment by luntik2012** [comment]
I think it's deprecated for now:) It seems I can compile it with --threads:on for now, but I really don't understand, how could it change jester's behaviour(I'm not god of Nim)
