### ISSUE TITLE
Jester resp block problem

### ISSUE THREAD

**Issue by lihf8515** [dom96/jester#56]
Me to do a program with the jester, in get block using resp to the client returns the data, when a small amount of data, the client can receive a normal. Why the amount of data is very big, such as a tens of KB, the client will not receive?

**Comment by Xe** [comment]
Can you show example code?

**Comment by lihf8515** [comment]
import jester, asyncdispatch, threadpool, cgi, encodings
import db_odbc

proc cx(mysql:string) :string {.thread.} =
  var jsonstr="["
  var isFirstRow:bool = true
  var theDb = open("dbpos", "dbcxj", "dbcxj", "dbpos")
  for row in theDb.fastRows(sql(mysql)):
    if isFirstRow:
      jsonstr.add "{"
      isFirstRow=false
    else:
      jsonstr.add ",{"
    jsonstr.add "\"goodsid\":\"" & $row[0] & "\","
    jsonstr.add "\"barcode\":\"" & $row[1] & "\","
    jsonstr.add "\"goodslname\":\"" & $row[2] & "\","
    jsonstr.add "\"adviceprice\":\"" & $row[3] & "\","
    jsonstr.add "\"cbsj\":\"" & $row[4] & "\","
    jsonstr.add "\"bb\":\"" & $row[5] & "\","
    jsonstr.add "\"qty\":\"" & $row[6] & "\","
    jsonstr.add "\"shopid\":\"" & $row[7] & "\"}"
  jsonstr.add "]"
  theDb.close()
  result= jsonstr

proc isComplete(fv:FlowVar[system.string]):Future[string]{.async.}=
  await sleepAsync(10)
  while true: #不停的查询线程执行的状态，直到执行完成，返回查询结果
    if isReady(fv):
      result = ^fv
      break
    await sleepAsync(10)

settings:
  port = Port(5000)
  appName = "/bookcx"
  bindAddr = "127.0.0.1"

routes:
  get "/cx/?@isbn?/?@sm?/?":
    if (@"isbn" == nil or @"isbn" == "") and (@"sm" == nil or @"sm" == ""):
      resp "[]","text/html;charset=gb2312"
    else:
      var sql="select goods.goodsid,goods.barcode,goods.goodslname,goods.adviceprice,goods.cbsj,goods.bb,"&
        "shopstock.qty,shopstock.shopid from goods left join shopstock on goods.goodsid=shopstock.goodsid "&
        "where shopstock.qty is not null"
      if @"isbn" != nil and @"isbn" != "":
        sql.add " and goods.barcode='" & @"isbn" & "'"
      if @"sm" != nil and @"sm" != "":
        # 将url编码解码后变为utf-8，再将utf-8转码为当前系统编码gb2312
        var sm=cgi.decodeUrl(@"sm").convert(encodings.getCurrentEncoding(),"UTF-8")
        sql.add " and goods.goodslname like '%" & sm & "%'"
      echo sql
      var fv= spawn cx(sql) #开新线程用来查询
      var dat= await isComplete(fv) #等待查询线程结束并返回查询结果
      resp $dat,"text/html;charset=gb2312" #向客户端发送结果

runForever()

**Comment by lihf8515** [comment]
[code.docx](https://github.com/dom96/jester/files/156360/code.docx)

**Comment by lihf8515** [comment]
Sorry! I got it wrong, I have a problem with my code.
