### ISSUE TITLE
Participate in Todo-Backend project

### ISSUE THREAD

**Issue by mfirry** [dom96/jester#57]
Hi, sorry for the silly request but I thought I should at least suggest you guys join the [Todo-Backend](http://www.todobackend.com).

**Comment by dom96** [comment]
That's pretty cool. Maybe you (or someone else) could implement a Jester version? :)

**Comment by codyebberson** [comment]
I took a crack at this:  https://github.com/codyebberson/nim-todobackend/blob/master/todobackend.nim

It requires HTTP PATCH, which is not in the current release, so you need to build Jester from source.

The code passes all tests on:  http://www.todobackend.com/specs/index.html

It uses an in-memory json JArray for the backing, which would be silly for production, but is good enough for a quick demo.

I'm pretty inexperienced with both Nim and Jester, so I'd happily welcome feedback from an expert.

@mfirry @dom96

**Comment by dom96** [comment]
Looks good! Surprised it's that simple :)

Btw, Jester still has no tagged version (yeah, I need to fix that I know), so whatever you are using you are always using it from source.

**Comment by mfirry** [comment]
Not experienced at all. I'll give it a look anyways.

**Comment by mfirry** [comment]
Feel free to close this.
