### ISSUE TITLE
Reading form data

### ISSUE THREAD

**Issue by andreaferretti** [dom96/jester#58]
Hi, is there a way to get the parameters of a request with type `application/x-www-form-urlencoded`? Or should one parse them by hand? I think that should a pretty standard way to pass form parameters

**Comment by Xe** [comment]
```nimrod
  post "/submit":
    try:
      var
        username = $(request.formData.mget "username").body
        url = $(request.formData.mget "url").body

      db.updateTweetsByUser(username, url)
      db.exec(sql"insert into users values (null, ?, ?)", username, url)
      db.exec(sql"insert into tweets values (null, 'twtxtlist', ?, ?)",
              $(getTime().getGMTime().timeinfoToTime().toSeconds()),
              "Added user @<" & username & " " & url & ">")

      redirect "/users/" & username & "/0"
    except: fail()
```

[taken from here](https://git.xeserv.us/xena/twtxtlist/src/master/src/twtxtlist.nim#L96-L109)

**Comment by andreaferretti** [comment]
Nope, what I get in `request.formData` is an empty table. According to the README, `formData` is populated only for a content-type of `multipart/form-data`. The usual url encoded format does not seem to be supported

**Comment by dom96** [comment]
You should be able to use ``@``:

```nim
get "/":
  echo(@"q") # -> "foo" for http://localhost:5000/?q=foo
```

**Comment by andreaferretti** [comment]
I am not talking about querystring parameters in a GET request. I am talking about form parameters in a POST request. The actual thing that gets sent to the server when clicking submit on a [HTML form](http://stackoverflow.com/questions/2436716/is-application-x-www-form-urlencoded-default-for-html-form)

**Comment by dom96** [comment]
Something like this? https://github.com/dom96/jester/blob/master/tests/alltest.nim#L65L79

**Comment by andreaferretti** [comment]
I just checked, and in fact form parameters can be retrieved via `@"parameter-name"`. :-)

I think it would be useful to document this (by the way, I could not find a way to distinguish them from url or querystring parameters with the same name).

I am not sure what the example you linked is about. Are you testing it by opening in a browser? If so, I would expect it to fail to extract the form data

**Comment by dom96** [comment]
> I think it would be useful to document this

PRs welcome ;)

> (by the way, I could not find a way to distinguish them from url or querystring parameters with the same name).

That _may_ be a problem, but can't you simply rename one of those?

> I am not sure what the example you linked is about. Are you testing it by opening in a browser? If so, I would expect it to fail to extract the form data

Not sure why you would expect it to fail, it's a simple form and when you submit it you are shown where the data is stored.

**Comment by andreaferretti** [comment]
Yeah, of course one can avoid the name clash. It is not an actual issue I have, just an observation.

The reason I expect it to fail is that when posting a form from the browser the content is url-encoded, and as far as I can tell `request.formData` is only populated for multipart forms

**Comment by dom96** [comment]
> The reason I expect it to fail is that when posting a form from the browser the content is url-encoded, and as far as I can tell request.formData is only populated for multipart forms

It's just an example so if ``formData`` is empty it will just display ``{}``.

**Comment by andreaferretti** [comment]
Understood. I think I can close this issue, thank you for the help :-)

**Comment by dom96** [comment]
Np :)
