### ISSUE TITLE
`attachment` failed to reply

### ISSUE THREAD

**Issue by shawnye** [dom96/jester#59]
The followying code is built on nim 0.13:
<pre>
import jester,asyncdispatch

settings:
    port = Port(8081)
    staticDir = "./static"

routes:
  get "/attachment/@id":
    echo "attachment=" & @"id"
    attachment "pages/login.html" #error occurred
    resp "done"

when isMainModule:
  echo "starting web server ..."
  runForever()
</pre>

when browser:
`http://localhost:8081/attachment/1`
eror occurred on page:
<pre>
Detail: Traceback (most recent call last)
gist.nim(18) gist
asyncdispatch.nim(1617) runForever
asyncdispatch.nim(446) poll
asyncdispatch.nim(722) :anonymous
asyncdispatch.nim(213) complete
asyncdispatch.nim(1257) cb
asyncnet.nim(320) recvLineIntoIter
asyncdispatch.nim(222) complete
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1262) cb
asyncdispatch.nim(260) callback=
asyncdispatch.nim(1257) cb
asynchttpserver.nim(238) processClientIter
jester.nim(330) :anonymous
jester.nim(301) handleHTTPRequest
asyncdispatch.nim(1270) handleRequest
asyncdispatch.nim(1257) cb
jester.nim(265) handleRequestIter
asyncdispatch.nim(1270) match
asyncdispatch.nim(1257) cb
jester.nim(444) matchIter
strtabs.nim(109) []
key not found: Content-Type
</pre>

What happened?

**Comment by shawnye** [comment]
console debug:
<pre>
DEBUG get /attachment/1
attachment=1
DEBUG   502 Bad Gateway {Content-Length: 1620, Content-Type: text/html;charset=utf-8}
</pre>

**Comment by shawnye** [comment]
line 444 in jester.nim:
    `if not (response.data[2]["Content-Type"] != "" or ext == ""):`

**Comment by shawnye** [comment]
I have change the line 444:
<pre>
    #line 444  if not (response.data[2]["Content-Type"] != "" or ext == ""):
    let ct = response.data[2].getOrDefault("Content-Type")
    if  (ct != nil and ct != "" and ext != ""):
</pre>

rebuild and run ,it is OK

**Comment by dom96** [comment]
The implementation of `[]` recently changed in Nim, so yeah, that looks like a valid fix.

**Comment by shawnye** [comment]
In fact , I hope The implementation of `[]` return nil or default value instead of raising the exception when not found, as getOrDefault() does. For the reason of it , I use much more `getOrDefault()` than `[]` ,which is inconvenient.

**Comment by dom96** [comment]
> I hope The implementation of [] return nil or default value instead of raising the exception when not found

It used to, but that was changed recently. ``getOrDefault`` behaves this way now.

Think you could open a PR to fix this?

**Comment by dom96** [comment]
Fixed via #62
