### ISSUE TITLE
Empty request params with XmlHTTP Post request

### ISSUE THREAD

**Issue by SSPkrolik** [dom96/jester#64]
When I try to perform POST request with Ajax, the server hangs eating 94% to 100% of the CPU core on Ubuntu 14.10.

Here's client's script, which works (`GET` request, and if we change it to `POST`, jester hangs):
```javascript
	jQuery.ajax({
		contentType: 'application/json',
		dataType: 'json',
		data: {
			userId: document.getElementById('user-id').value
		},
		type: 'GET',
		url: '/handle-this',

		success: function(data) {
			switch (data["result"]) {
			case -2:
			    alert("malformed json");
			case -1:
				alert("Bad session id");
			case  0:
				alert("Success");
			}
		},

		error: function() {
			alert("Error saving cheat response");
		}
	});
```
and the server handler:
```nim
echo request.params    # Prints: {:}
try:
    sessId = request.params["userId"]
    echo sessId
except:
    respJson Http200, """{"result": -1}"""
```

Everything works fine with `GET` request (parameters are parsed and passed into handler), and does not work with `POST` request, parameters are empty and the server hangs at `sessId = request.params["userId"]` line.

**Comment by SSPkrolik** [comment]
Also formData is empty when using `POST`

**Comment by dom96** [comment]
What's the stack trace when you terminate the app via Ctrl+C?

**Comment by SSPkrolik** [comment]
@dom96 There's no stacktrace, and the app does not react to interrupt signal (Ctrl+C). Only `kill -9` helps. I've found that it happens whan there's uncatched exception thrown, and seems like the app is stuck in signal handler or so ...

**Comment by dom96** [comment]
Strange. Maybe you could run it in gdb to get more information about what the cause is?

**Comment by SSPkrolik** [comment]
After some investigation we have narrowed the problem to the #65 case. Closing this one.
