### ISSUE TITLE
Update for Nim 0.14

### ISSUE THREAD

**Issue by andreaferretti** [dom96/jester#69]
With the latest changes to HTTP headers, Jester does not work on latest Nim stable

**Comment by dom96** [comment]
Are you sure, I fixed this stuff in https://github.com/dom96/jester/commit/3cbe21d67c686613dbade63ef435d80f5b8e70df

**Comment by andreaferretti** [comment]
You are right, but then you should bump version, otherwise people having
installed version 0.1 won't see the upgrade. And maybe you could also tag
versions :-)

Il venerdì 10 giugno 2016, Dominik Picheta <notifications@github.com> ha
scritto:

**Comment by dom96** [comment]
Yes, I need to *finally* tag a version.

**Comment by alphashuro** [comment]
lol its been a month now and yet no tagged version

**Comment by dom96** [comment]
Yep. It's what happens when you have 1001 projects plus a book to write.

**Comment by alphashuro** [comment]
Lol you've finished the book though right? So only 1001 projects left. Also, do you have a platform for feedback on the book? I have some comments I'd like to make.

**Comment by dom96** [comment]
No. I haven't. Why do you think that?

There is plenty. The Nim forum (http://forum.nim-lang.org/t/1978/13) or the Manning forum.

**Comment by alphashuro** [comment]
because you're selling it? :O will i get the updated one when you add content?

**Comment by dom96** [comment]
The book is in MEAP, which stands for Manning *Early Access* Programme (emphasis on the "early access")

**Comment by dom96** [comment]
And yes, once you buy it you will get updates as its written.

**Comment by alphashuro** [comment]
lol 💔 i feel stupid now

**Comment by alphashuro** [comment]
okay awesome so i _didn't_ make a mistake then :) i will try to contribute to your documentation as much as i can, i've fallen for nim now

**Comment by andreaferretti** [comment]
Well, you just need to edit the version number in `jester.nimble` and `git tag 0.1.1` the project - I guess that replying to this thread took more time :-)

**Comment by dom96** [comment]
Well, I wanted to implement some remaining things before tagging... but I should stop doing that. I will tag 0.1.0 now.

**Comment by andreaferretti** [comment]
Well, actually 0.1.1. People using a previous version of Jester already have downloaded 0.1.0 and will not be able to get the latest release (short of uninstalling manually jester from nimble, but it will not be obvious to most users).

In short, adding even a minor tag for every change helps people to upgrade

**Comment by dom96** [comment]
I simply tagged `0.1.0`.

**Comment by dom96** [comment]
I don't think a bumping is required.

**Comment by dom96** [comment]
Wow. Something incredibly wrong is going on with Github and it has just really confused me. After a refresh my comment disappeared, so I made a new one and now the new one has disappeared. 
<img width="790" alt="screen shot 2016-07-12 at 17 10 28" src="https://cloud.githubusercontent.com/assets/246651/16774396/a8b7e5d6-4853-11e6-85bc-a364a0069685.png">
<img width="726" alt="screen shot 2016-07-12 at 17 10 08" src="https://cloud.githubusercontent.com/assets/246651/16774395/a8b6af86-4853-11e6-8dae-9b2a3c1331ce.png">
