### ISSUE TITLE
Custom 404 response?

### ISSUE THREAD

**Issue by gekkonier** [dom96/jester#70]
I would like to use a custom 404 response.

Maybe like this?

```
import jester, asyncdispatch

errorpages:
  pagenotfound:
    resp "nothing found"

routes:
  get "/":
    resp "hello, world!"

runForever()
```

**Comment by farazfazli** [comment]
Maybe just setting a variable to the path of a 404 page to override default behavior. Would really appreciate this @gekkonier!

**Comment by farazfazli** [comment]
Maybe just setting a variable to the path of a 404 page to override default behavior. Would really appreciate this @dom96!

**Comment by jshulver** [comment]
The following specified after other paths seems to work for me. Not sure if the order matters or not. I've not experimented much further but the server/notfound/secondpathpart doesn't work with this method - maybe a regex would work? Would be better if this was built-in functionality though.
`  get "/@notFound":
    resp Http404, "404"
`

**Comment by dom96** [comment]
That's a nice workaround. A regex would definitely work.

**Comment by dom96** [comment]
This is now implemented.
