### ISSUE TITLE
documentation :(

### ISSUE THREAD

**Issue by alphashuro** [dom96/jester#73]
your documentation only shows basic examples for responding with "hello world" stuff, and your book focuses on server rendered applications. however, some people (such as i) would like to build single page apps and build a backend api with jester. can you provide some documentation examples for sending status codes for example, because i tried doing `status = 200` and it failed which was very confusing because it requires an HttpCode which cannot be found on google. now i'm using `status = Http400` but i'm getting a 404 instead. still struggling on to find out how to do a simple status code :( please try to cater for api developers rather than just for server rendered apps, i'm sure most of the apps built these days are SPAs anyway...

**Comment by alphashuro** [comment]
Can you create a gh-pages branch and host the docs generated by `nim doc jester.nim`, I believe that would be a perfect place to put them :D

**Comment by Xe** [comment]
Why is this closed? It's still an issue.

**Comment by dom96** [comment]
Closed again? Why?

**Comment by alphashuro** [comment]
it is no longer relevant to me and i would like to stop seeing it on my issue list. the fact that it hasn’t been actioned in this much time means it’s likely going to be in this state for a long time, and i don’t get value from seeing it every day. please reopen it from your github account if it is relevant to you

**Comment by alphashuro** [comment]
it is no longer relevant to me and i would like to stop seeing it on my issue list. the fact that it hasn’t been actioned in this much time means it’s likely going to be in this state for a long time, and i don’t get value from seeing it every day. please reopen it from your github account if it is relevant to you
