### ISSUE TITLE
multiple excepts

### ISSUE THREAD

**Issue by alphashuro** [dom96/jester#75]
so it seems jester's macros break when trying to use more than 1 `except` statements.

**Comment by dom96** [comment]
Was this fixed?

**Comment by alphashuro** [comment]
Nope, but no one responded

**Comment by dom96** [comment]
So why close it? Just because someone hasn't responded yet doesn't mean nobody will.

**Comment by alphashuro** [comment]
I was cleaning up my account, and didn't see this going anywhere... I can reop

**Comment by alphashuro** [comment]
its been 2 years, i think its safe to assume noone will respond to this

**Comment by dom96** [comment]
It's not.

**Comment by alphashuro** [comment]
if you would like, please recreate the issue from your github account, it’s no longer relevant to me and i would like to stop seeing it on my issue list.

**Comment by dom96** [comment]
Can't you simply unsubscribe from it?

**Comment by alphashuro** [comment]
it still shows up on my issues list.

**Comment by dom96** [comment]
Where do you access this issue list?

**Comment by alphashuro** [comment]
the button on Github's navbar,linking to https://github.com/issues

**Comment by dom96** [comment]
meh, alright.
