### ISSUE TITLE
How to stop gracefully when SIGINT, SIGHUP or SIGTERM is received ?

### ISSUE THREAD

**Issue by takaomag** [dom96/jester#77]
Hi,

I want to write an http server application using jester.
Can someone tell me the proper way to stop jester gracefully when it receives SIGINT , SIGHUP or SIGTERM?

**Comment by Xe** [comment]
define "gracefully"

**Comment by nigredo-tori** [comment]
Depending on what you need:
1. Use `addQuitProc` from `system` to save your state/output messages/stop async dispatching ("stop" jester). Try using `waitFor` instead of `runForever` for your dispatch loop since it can be stopped.
2. Roll your own signal handlers for full control: https://github.com/nim-lang/Nim/blob/57c52d05df6012a1a0e8577e255e61d1329c3a26/lib/system/excpt.nim#L318
Both of these have little to do with jester itself.

**Comment by dom96** [comment]
Using ``addQuitProc`` is likely the way to go.

**Comment by takaomag** [comment]
Thanks, all.


- **first attempt code**
```nim
import jester, asyncdispatch, htmlgen

var is_running = true

proc at_exit() {.noconv.} =
    echo "signal received"
    is_running = false

addQuitProc(at_exit)

routes:
  get "/":
    resp h1("Hello world")


while is_running:
    echo "poll start"
    poll(1000)
    echo "poll end"

poll()
echo "stopped"
quit(QuitSuccess)
```

- **result**
```
INFO Jester is making jokes at http://localhost:5000
poll start
poll end
poll start
poll end
poll start
^CTraceback (most recent call last)
test1.nim(19)            test1
asyncdispatch.nim(1284)  poll
selectors.nim(158)       select
SIGINT: Interrupted by Ctrl-C.
signal received
Error: execution of an external program failed: ' 'test0'
```

It seems my handler does not handle signal properly.

- **second attempt code**
```nim
import jester, asyncdispatch, htmlgen, posix


var is_running = true

proc c_signal(sig: cint, handler: proc (a: cint) {.noconv.}) {.importc: "signal", header: "<signal.h>".}

proc at_exit(sig: cint) {.noconv.} =
    echo "signal received"
    is_running = false

c_signal(SIGINT, at_exit)

routes:
  get "/":
    resp h1("Hello world")


while is_running:
    echo "poll start"
    poll(1000)
    echo "poll end"

poll()
echo "stopped"
quit(QuitSuccess)
```

- **result**
```
INFO Jester is making jokes at http://localhost:5000
poll start
poll end
poll start
poll end
poll start
^Csignal received
poll end
stopped
```

It seems OK. However, I guess the server socket of the asynchttpserver MUST be closed at first. While the server socket is open, a client may send request even after SIGINT is received.

But, I can not find the way to close jester's server socket since jes is private.

**Comment by nigredo-tori** [comment]
The reason the first attempt doesn't work as intended is that it doesn't stop Nim from handling the signal. You could wait until the server is stopped inside `at_exit`, but that sounds ugly.
Actually, if you're only interested in Ctrl+C hook, the best solution would be to use `setControlCHook` - it prevents Nim from terminating the program, so you're free to terminate however you see fit (or not terminate at all).

**Comment by FedericoCeratto** [comment]
To handle multiple signals on UNIX there's: 
http://nim-lang.org/docs/posix.html#onSignal.t,varargs%5Bcint%5D,untyped
