### ISSUE TITLE
`attachment` either not working or mis-documented

### ISSUE THREAD

**Issue by nigredo-tori** [dom96/jester#81]
`attachment` template has the following in its documentation comment: 

> Once the route exits, `filename` will be sent to the person making the request ...

which leads to believe that the filename would be saved somewhere, and the file will be sent automatically (probably via multipart response). In reality, though, the template only sets the headers, leaving it to programmer to actually send the file.
Even the tests are misleading:

``` nim
  get "/attachment":
    attachment "public/root/index.html"
    resp "blah"
```

```
$ curl -v -v http://127.0.0.1:5454/foo/attachment
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 5454 (#0)
> GET /foo/attachment HTTP/1.1
> Host: 127.0.0.1:5454
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 4
< Content-Type: text/html;charset=utf-8
< Content-Disposition: attachment; filename="index.html"
< 
* Connection #0 to host 127.0.0.1 left intact
blah
```

**Comment by shawnye** [comment]
see #90 , there maybe the answer.

**Comment by nigredo-tori** [comment]
@shawnye, not really. `Content-Type` not being set has nothing to do with the fact that the template's code does not even read the file.
This issue is just a documentation vs reality problem. We should either change `attachment`'s documentation to describe its behavior, or change behavior to match documentation.

**Comment by shawnye** [comment]
You are right.

I use code:
<pre>
get "/attachment":
    attachment "public/root/test.doc"
    resp readFile "public/root/test.doc"
</pre>

It uses a lot of memory and maybe never release it
