### ISSUE TITLE
Template `attachment` has problem when setting `Content-Type`

### ISSUE THREAD

**Issue by shawnye** [dom96/jester#90]
<pre>
let ext = splitFile(filename).ext
    if not response.data[2].hasKey("Content-Type") and ext != "":
      response.data[2]["Content-Type"] = getMimetype(request.settings.mimes, ext)
</pre>

Because `ext` contains prefix '.' ,can not get any mimetype from MimeDb

**Comment by dom96** [comment]
Seems to be working fine to me?
