### ISSUE TITLE
Add routes and serve alternatives that return Future

### ISSUE THREAD

**Issue by nigredo-tori** [dom96/jester#91]
Current `routes` and `serve` don't expose the future they received from `asynchttpserver.serve`. This means that API user can't handle corresponding errors locally - they are propagated all the way to `poll`/`waitFor`/`runForever`.
Since making `routes` and `serve` return a `Future` would break a lot of code (all of it, I imagine), it would make sense to add new functions that return futures rather than modifying the existing ones.

**Comment by dom96** [comment]
I have fixed this differently. Note that the fix will only work for asynchttpserver.

**Comment by nigredo-tori** [comment]
@dom96, what's your fix exactly? If you're talking about the `errorFilter` - it solves only a part of the problem. There's still no nice way to catch the errors raised in `asynchttpserver.serve` itself (e.g. when binding to a socket). So if I want to, say, gracefully terminate in case the server fails to start, I'll have to catch any exceptions that fall out of `runForever`, and guess which ones signal that the server stopped working, instead of just using `waitFor`.

I'll look at the code later at work to see what exactly was the problem in my case (it's been a year, after all), but off the top of my head that was it.

**Comment by dom96** [comment]
https://github.com/dom96/jester/commit/c1983d085900ae99c49caf8eefde5c5ab0365adf

**Comment by nigredo-tori** [comment]
Okay, this seems a bit unintuitive, but it should get the job done. Thank you.
