### ISSUE TITLE
Timeout on routes?

### ISSUE THREAD

**Issue by jivank** [dom96/jester#96]
Is it possible to have a route interrupt itself if it doesn't reach its return statement after X amount of seconds?

**Comment by dom96** [comment]
I don't think so, maybe you could tell me more about what you are trying to do?

**Comment by jivank** [comment]
Here is a python solution:
http://stackoverflow.com/questions/2281850/timeout-function-if-it-takes-too-long-to-finish
This seems related:
http://nim-lang.org/docs/asyncdispatch.html#withTimeout,Future[T],int

Sometimes a route will get stuck and will hang the application until you hit CTRL-C (this will interrupt the route and not kill jester) . So rather than use a supervisor that will restart the process when it hangs, it might be useful to be able to specify a timeout duration. Perhaps this can done without modifying jester, similar to the python solution.

**Comment by dom96** [comment]
Yeah, ``withTimeout`` is exactly what you need. You can move the code that may take too long into an async proc and call it using ``withTimeout`` inside your route.
